"""
Seed the bestiary table with SRD 5.1 creatures.
Run: uv run python scripts/seed_bestiary.py
"""
import asyncio
import json
import sys
from pathlib import Path

# Add backend to path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "backend"))

from app.db import connect_db, close_db, get_pool

# ── SRD Creature data ─────────────────────────────────────────────────────

CREATURES = [
    {
        "name": "Goblin", "type": "humanoid", "size": "small", "alignment": "neutral evil",
        "cr": 0.25, "xp": 50, "ac": 15, "ac_type": "leather armor, shield",
        "hp": "7 (2d6)", "hp_avg": 7, "speed": "30 ft.",
        "str": 8, "dex": 14, "con": 10, "int": 10, "wis": 8, "cha": 8,
        "skills": "Stealth +6", "saves": None,
        "senses": "darkvision 60 ft., passive Perception 9",
        "languages": "Common, Goblin",
        "environment": ["forest", "grassland", "underdark"],
        "traits": [{"name": "Nimble Escape", "desc": "The goblin can take the Disengage or Hide action as a bonus action on each of its turns."}],
        "actions": [
            {"name": "Scimitar", "desc": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) slashing damage."},
            {"name": "Shortbow", "desc": "Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Hobgoblin", "type": "humanoid", "size": "medium", "alignment": "lawful evil",
        "cr": 0.5, "xp": 100, "ac": 18, "ac_type": "chain mail, shield",
        "hp": "11 (2d8+2)", "hp_avg": 11, "speed": "30 ft.",
        "str": 13, "dex": 12, "con": 12, "int": 10, "wis": 10, "cha": 9,
        "skills": None, "saves": None,
        "senses": "darkvision 60 ft., passive Perception 10",
        "languages": "Common, Goblin",
        "environment": ["forest", "grassland", "underdark"],
        "traits": [{"name": "Martial Advantage", "desc": "Once per turn, the hobgoblin can deal an extra 7 (2d6) damage to a creature it hits with a weapon attack if that creature is within 5 ft. of an ally of the hobgoblin that isn't incapacitated."}],
        "actions": [
            {"name": "Longsword", "desc": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 5 (1d8 + 1) slashing damage, or 6 (1d10 + 1) slashing damage if used with two hands."},
            {"name": "Longbow", "desc": "Ranged Weapon Attack: +3 to hit, range 150/600 ft., one target. Hit: 5 (1d8 + 1) piercing damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Bugbear", "type": "humanoid", "size": "medium", "alignment": "chaotic evil",
        "cr": 1, "xp": 200, "ac": 16, "ac_type": "hide armor, shield",
        "hp": "27 (5d8+5)", "hp_avg": 27, "speed": "30 ft.",
        "str": 15, "dex": 14, "con": 13, "int": 8, "wis": 11, "cha": 9,
        "skills": "Stealth +6, Survival +2", "saves": None,
        "senses": "darkvision 60 ft., passive Perception 10",
        "languages": "Common, Goblin",
        "environment": ["forest", "grassland", "underdark"],
        "traits": [
            {"name": "Brute", "desc": "A melee weapon deals one extra die of its damage when the bugbear hits with it (included in the attack)."},
            {"name": "Surprise Attack", "desc": "If the bugbear surprises a creature and hits it with an attack during the first round of combat, the target takes an extra 7 (2d6) damage from the attack."},
        ],
        "actions": [
            {"name": "Morningstar", "desc": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 11 (2d8 + 2) piercing damage."},
            {"name": "Javelin", "desc": "Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 5 (1d6 + 2) piercing damage in melee or 9 (2d6 + 2) piercing damage at range."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Orc", "type": "humanoid", "size": "medium", "alignment": "chaotic evil",
        "cr": 0.5, "xp": 100, "ac": 13, "ac_type": "hide armor",
        "hp": "15 (2d8+6)", "hp_avg": 15, "speed": "30 ft.",
        "str": 16, "dex": 12, "con": 16, "int": 7, "wis": 11, "cha": 10,
        "skills": "Intimidation +2", "saves": None,
        "senses": "darkvision 60 ft., passive Perception 10",
        "languages": "Common, Orc",
        "environment": ["forest", "grassland", "mountain"],
        "traits": [{"name": "Aggressive", "desc": "As a bonus action, the orc can move up to its speed toward a hostile creature that it can see."}],
        "actions": [
            {"name": "Greataxe", "desc": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 9 (1d12 + 3) slashing damage."},
            {"name": "Javelin", "desc": "Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 6 (1d6 + 3) piercing damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Kobold", "type": "humanoid", "size": "small", "alignment": "lawful evil",
        "cr": 0.125, "xp": 25, "ac": 12, "ac_type": None,
        "hp": "5 (2d6-2)", "hp_avg": 5, "speed": "30 ft.",
        "str": 7, "dex": 15, "con": 9, "int": 8, "wis": 7, "cha": 8,
        "skills": None, "saves": None,
        "senses": "darkvision 60 ft., passive Perception 8",
        "languages": "Common, Draconic",
        "environment": ["forest", "mountain", "underdark"],
        "traits": [
            {"name": "Sunlight Sensitivity", "desc": "While in sunlight, the kobold has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight."},
            {"name": "Pack Tactics", "desc": "The kobold has advantage on an attack roll against a creature if at least one of the kobold's allies is within 5 ft. of the creature and the ally isn't incapacitated."},
        ],
        "actions": [
            {"name": "Dagger", "desc": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 4 (1d4 + 2) piercing damage."},
            {"name": "Sling", "desc": "Ranged Weapon Attack: +4 to hit, range 30/120 ft., one target. Hit: 4 (1d4 + 2) bludgeoning damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Skeleton", "type": "undead", "size": "medium", "alignment": "lawful evil",
        "cr": 0.25, "xp": 50, "ac": 13, "ac_type": "armor scraps",
        "hp": "13 (2d8+4)", "hp_avg": 13, "speed": "30 ft.",
        "str": 10, "dex": 14, "con": 15, "int": 6, "wis": 8, "cha": 5,
        "skills": None, "saves": None,
        "damage_vulnerabilities": "bludgeoning",
        "damage_immunities": "poison",
        "condition_immunities": "exhaustion, poisoned",
        "senses": "darkvision 60 ft., passive Perception 9",
        "languages": "understands all languages it knew in life but can't speak",
        "environment": ["underdark", "urban"],
        "traits": [],
        "actions": [
            {"name": "Shortsword", "desc": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage."},
            {"name": "Shortbow", "desc": "Ranged Weapon Attack: +4 to hit, range 80/320 ft., one target. Hit: 5 (1d6 + 2) piercing damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Zombie", "type": "undead", "size": "medium", "alignment": "neutral evil",
        "cr": 0.25, "xp": 50, "ac": 8, "ac_type": None,
        "hp": "22 (3d8+9)", "hp_avg": 22, "speed": "20 ft.",
        "str": 13, "dex": 6, "con": 16, "int": 3, "wis": 6, "cha": 5,
        "skills": None, "saves": "Wis +0",
        "damage_immunities": "poison",
        "condition_immunities": "poisoned",
        "senses": "darkvision 60 ft., passive Perception 8",
        "languages": "understands all languages it knew in life but can't speak",
        "environment": ["swamp", "underdark", "urban"],
        "traits": [{"name": "Undead Fortitude", "desc": "If damage reduces the zombie to 0 hit points, it must make a Constitution saving throw with a DC of 5 + the damage taken, unless the damage is radiant or from a critical hit. On a success, the zombie drops to 1 hit point instead."}],
        "actions": [
            {"name": "Slam", "desc": "Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) bludgeoning damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Ghoul", "type": "undead", "size": "medium", "alignment": "chaotic evil",
        "cr": 1, "xp": 200, "ac": 12, "ac_type": None,
        "hp": "22 (5d8)", "hp_avg": 22, "speed": "30 ft.",
        "str": 13, "dex": 15, "con": 10, "int": 7, "wis": 10, "cha": 6,
        "skills": None, "saves": None,
        "damage_immunities": "poison",
        "condition_immunities": "charmed, exhaustion, poisoned",
        "senses": "darkvision 60 ft., passive Perception 10",
        "languages": "Common",
        "environment": ["swamp", "underdark", "urban"],
        "traits": [],
        "actions": [
            {"name": "Bite", "desc": "Melee Weapon Attack: +2 to hit, reach 5 ft., one creature. Hit: 9 (2d6 + 2) piercing damage."},
            {"name": "Claws", "desc": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (2d4 + 2) slashing damage. If the target is a creature other than an elf or undead, it must succeed on a DC 10 Constitution saving throw or be paralyzed for 1 minute."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Wight", "type": "undead", "size": "medium", "alignment": "neutral evil",
        "cr": 3, "xp": 700, "ac": 14, "ac_type": "studded leather",
        "hp": "45 (6d8+18)", "hp_avg": 45, "speed": "30 ft.",
        "str": 15, "dex": 14, "con": 16, "int": 10, "wis": 13, "cha": 15,
        "skills": "Perception +3, Stealth +4", "saves": None,
        "damage_resistances": "necrotic; bludgeoning, piercing, and slashing from nonmagical attacks",
        "damage_immunities": "poison",
        "condition_immunities": "exhaustion, poisoned",
        "senses": "darkvision 60 ft., passive Perception 13",
        "languages": "the languages it knew in life",
        "environment": ["swamp", "underdark"],
        "traits": [{"name": "Sunlight Sensitivity", "desc": "While in sunlight, the wight has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight."}],
        "actions": [
            {"name": "Multiattack", "desc": "The wight makes two longsword attacks or two longbow attacks. It can use its Life Drain in place of one longsword attack."},
            {"name": "Life Drain", "desc": "Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 5 (1d6 + 2) necrotic damage. The target must succeed on a DC 13 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken."},
            {"name": "Longsword", "desc": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) slashing damage, or 7 (1d10 + 2) slashing damage if used with two hands."},
            {"name": "Longbow", "desc": "Ranged Weapon Attack: +4 to hit, range 150/600 ft., one target. Hit: 6 (1d8 + 2) piercing damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Owlbear", "type": "monstrosity", "size": "large", "alignment": "unaligned",
        "cr": 3, "xp": 700, "ac": 13, "ac_type": "natural armor",
        "hp": "59 (7d10+21)", "hp_avg": 59, "speed": "40 ft.",
        "str": 20, "dex": 12, "con": 17, "int": 3, "wis": 12, "cha": 7,
        "skills": "Perception +3", "saves": None,
        "senses": "darkvision 60 ft., passive Perception 13",
        "languages": "—",
        "environment": ["forest"],
        "traits": [{"name": "Keen Sight and Smell", "desc": "The owlbear has advantage on Wisdom (Perception) checks that rely on sight or smell."}],
        "actions": [
            {"name": "Multiattack", "desc": "The owlbear makes two attacks: one with its beak and one with its claws."},
            {"name": "Beak", "desc": "Melee Weapon Attack: +7 to hit, reach 5 ft., one creature. Hit: 10 (1d10 + 5) piercing damage."},
            {"name": "Claws", "desc": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 14 (2d8 + 5) slashing damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Gelatinous Cube", "type": "ooze", "size": "large", "alignment": "unaligned",
        "cr": 2, "xp": 450, "ac": 6, "ac_type": None,
        "hp": "84 (8d10+40)", "hp_avg": 84, "speed": "15 ft.",
        "str": 14, "dex": 3, "con": 20, "int": 1, "wis": 6, "cha": 1,
        "skills": None, "saves": None,
        "condition_immunities": "blinded, charmed, deafened, exhaustion, frightened, prone",
        "senses": "blindsight 60 ft. (blind beyond this radius), passive Perception 8",
        "languages": "—",
        "environment": ["underdark"],
        "traits": [
            {"name": "Ooze Cube", "desc": "The cube takes up its entire space. Other creatures can enter the space, but a creature that does so is subjected to the cube's Engulf and has disadvantage on the saving throw. Creatures inside the cube can be seen but have total cover."},
            {"name": "Transparent", "desc": "Even when the cube is in plain sight, it takes a successful DC 15 Wisdom (Perception) check to spot a cube that has neither moved nor attacked."},
        ],
        "actions": [
            {"name": "Pseudopod", "desc": "Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 10 (3d6) acid damage."},
            {"name": "Engulf", "desc": "The cube moves up to its speed. While doing so, it can enter Large or smaller creatures' spaces. Whenever the cube enters a creature's space, the creature must make a DC 12 Dexterity saving throw. On a success, the creature can choose to be pushed 5 ft. back or to the side. On a failure, the cube enters the creature's space; the creature takes 10 (3d6) acid damage and is engulfed."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Mimic", "type": "monstrosity", "size": "medium", "alignment": "neutral",
        "cr": 2, "xp": 450, "ac": 12, "ac_type": "natural armor",
        "hp": "58 (9d8+18)", "hp_avg": 58, "speed": "15 ft.",
        "str": 17, "dex": 12, "con": 15, "int": 5, "wis": 13, "cha": 8,
        "skills": "Stealth +5", "saves": None,
        "damage_immunities": "acid",
        "condition_immunities": "prone",
        "senses": "darkvision 60 ft., passive Perception 11",
        "languages": "—",
        "environment": ["underdark", "urban"],
        "traits": [
            {"name": "Shapechanger", "desc": "The mimic can use its action to polymorph into an object or back into its true, amorphous form. Its statistics are the same in each form."},
            {"name": "Adhesive (Object Form Only)", "desc": "The mimic adheres to anything that touches it. A Huge or smaller creature adhered to the mimic is also grappled by it (escape DC 13). Ability checks made to escape this grapple have disadvantage."},
            {"name": "False Appearance (Object Form Only)", "desc": "While the mimic remains motionless, it is indistinguishable from an ordinary object."},
            {"name": "Grappler", "desc": "The mimic has advantage on attack rolls against any creature grappled by it."},
        ],
        "actions": [
            {"name": "Pseudopod", "desc": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) bludgeoning damage. If the mimic is in object form, the target is subjected to its Adhesive trait."},
            {"name": "Bite", "desc": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) piercing damage plus 4 (1d8) acid damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Troll", "type": "giant", "size": "large", "alignment": "chaotic evil",
        "cr": 5, "xp": 1800, "ac": 15, "ac_type": "natural armor",
        "hp": "84 (8d10+40)", "hp_avg": 84, "speed": "30 ft.",
        "str": 18, "dex": 13, "con": 20, "int": 7, "wis": 9, "cha": 7,
        "skills": "Perception +2", "saves": None,
        "senses": "darkvision 60 ft., passive Perception 12",
        "languages": "Giant",
        "environment": ["forest", "mountain", "swamp"],
        "traits": [
            {"name": "Keen Smell", "desc": "The troll has advantage on Wisdom (Perception) checks that rely on smell."},
            {"name": "Regeneration", "desc": "The troll regains 10 hit points at the start of its turn. If the troll takes acid or fire damage, this trait doesn't function at the start of the troll's next turn. The troll dies only if it starts its turn with 0 hit points and doesn't regenerate."},
        ],
        "actions": [
            {"name": "Multiattack", "desc": "The troll makes three attacks: one with its bite and two with its claws."},
            {"name": "Bite", "desc": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 7 (1d6 + 4) piercing damage."},
            {"name": "Claw", "desc": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) slashing damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Ogre", "type": "giant", "size": "large", "alignment": "chaotic evil",
        "cr": 2, "xp": 450, "ac": 11, "ac_type": "hide armor",
        "hp": "59 (7d10+21)", "hp_avg": 59, "speed": "40 ft.",
        "str": 19, "dex": 8, "con": 16, "int": 5, "wis": 7, "cha": 7,
        "skills": None, "saves": None,
        "senses": "darkvision 60 ft., passive Perception 8",
        "languages": "Common, Giant",
        "environment": ["forest", "grassland", "mountain"],
        "traits": [],
        "actions": [
            {"name": "Greatclub", "desc": "Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 13 (2d8 + 4) bludgeoning damage."},
            {"name": "Javelin", "desc": "Melee or Ranged Weapon Attack: +6 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 11 (2d6 + 4) piercing damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Hill Giant", "type": "giant", "size": "huge", "alignment": "chaotic evil",
        "cr": 5, "xp": 1800, "ac": 13, "ac_type": "natural armor",
        "hp": "105 (10d12+40)", "hp_avg": 105, "speed": "40 ft.",
        "str": 21, "dex": 8, "con": 19, "int": 5, "wis": 9, "cha": 6,
        "skills": "Perception +2", "saves": None,
        "senses": "passive Perception 12",
        "languages": "Giant",
        "environment": ["grassland", "mountain"],
        "traits": [],
        "actions": [
            {"name": "Multiattack", "desc": "The giant makes two greatclub attacks."},
            {"name": "Greatclub", "desc": "Melee Weapon Attack: +8 to hit, reach 10 ft., one target. Hit: 18 (3d8 + 5) bludgeoning damage."},
            {"name": "Rock", "desc": "Ranged Weapon Attack: +8 to hit, range 60/240 ft., one target. Hit: 21 (3d10 + 5) bludgeoning damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Fire Giant", "type": "giant", "size": "huge", "alignment": "lawful evil",
        "cr": 9, "xp": 5000, "ac": 18, "ac_type": "plate",
        "hp": "162 (13d12+78)", "hp_avg": 162, "speed": "30 ft.",
        "str": 25, "dex": 9, "con": 23, "int": 10, "wis": 14, "cha": 13,
        "skills": "Athletics +11, Perception +6", "saves": "Dex +3, Con +10, Cha +5",
        "damage_immunities": "fire",
        "senses": "passive Perception 16",
        "languages": "Giant",
        "environment": ["mountain", "underdark"],
        "traits": [],
        "actions": [
            {"name": "Multiattack", "desc": "The giant makes two greatsword attacks."},
            {"name": "Greatsword", "desc": "Melee Weapon Attack: +11 to hit, reach 10 ft., one target. Hit: 28 (6d6 + 7) slashing damage."},
            {"name": "Rock", "desc": "Ranged Weapon Attack: +11 to hit, range 60/240 ft., one target. Hit: 29 (4d10 + 7) bludgeoning damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Wyrmling Black Dragon", "type": "dragon", "size": "medium", "alignment": "chaotic evil",
        "cr": 2, "xp": 450, "ac": 17, "ac_type": "natural armor",
        "hp": "33 (6d8+6)", "hp_avg": 33, "speed": "30 ft., fly 60 ft., swim 30 ft.",
        "str": 15, "dex": 14, "con": 13, "int": 10, "wis": 11, "cha": 13,
        "skills": "Perception +4, Stealth +4", "saves": "Dex +4, Con +3, Wis +2, Cha +3",
        "damage_immunities": "acid",
        "senses": "blindsight 10 ft., darkvision 60 ft., passive Perception 14",
        "languages": "Draconic",
        "environment": ["swamp"],
        "traits": [{"name": "Amphibious", "desc": "The dragon can breathe air and water."}],
        "actions": [
            {"name": "Bite", "desc": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 7 (1d10 + 2) piercing damage plus 2 (1d4) acid damage."},
            {"name": "Acid Breath (Recharge 5-6)", "desc": "The dragon exhales acid in a 15-foot line that is 5 feet wide. Each creature in that line must make a DC 11 Dexterity saving throw, taking 22 (5d8) acid damage on a failed save, or half as much damage on a successful one."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Young Red Dragon", "type": "dragon", "size": "large", "alignment": "chaotic evil",
        "cr": 10, "xp": 5900, "ac": 18, "ac_type": "natural armor",
        "hp": "178 (17d10+85)", "hp_avg": 178, "speed": "40 ft., climb 40 ft., fly 80 ft.",
        "str": 23, "dex": 10, "con": 21, "int": 14, "wis": 11, "cha": 19,
        "skills": "Perception +8, Stealth +4", "saves": "Dex +4, Con +9, Wis +4, Cha +8",
        "damage_immunities": "fire",
        "senses": "blindsight 30 ft., darkvision 120 ft., passive Perception 18",
        "languages": "Common, Draconic",
        "environment": ["mountain"],
        "traits": [],
        "actions": [
            {"name": "Multiattack", "desc": "The dragon makes three attacks: one with its bite and two with its claws."},
            {"name": "Bite", "desc": "Melee Weapon Attack: +10 to hit, reach 10 ft., one target. Hit: 17 (2d10 + 6) piercing damage plus 3 (1d6) fire damage."},
            {"name": "Claw", "desc": "Melee Weapon Attack: +10 to hit, reach 5 ft., one target. Hit: 13 (2d6 + 6) slashing damage."},
            {"name": "Fire Breath (Recharge 5-6)", "desc": "The dragon exhales fire in a 30-foot cone. Each creature in that area must make a DC 17 Dexterity saving throw, taking 56 (16d6) fire damage on a failed save, or half as much damage on a successful one."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Adult Black Dragon", "type": "dragon", "size": "huge", "alignment": "chaotic evil",
        "cr": 14, "xp": 11500, "ac": 19, "ac_type": "natural armor",
        "hp": "195 (17d12+85)", "hp_avg": 195, "speed": "40 ft., fly 80 ft., swim 40 ft.",
        "str": 23, "dex": 14, "con": 21, "int": 14, "wis": 13, "cha": 17,
        "skills": "Perception +11, Stealth +7", "saves": "Dex +7, Con +10, Wis +6, Cha +8",
        "damage_immunities": "acid",
        "senses": "blindsight 60 ft., darkvision 120 ft., passive Perception 21",
        "languages": "Common, Draconic",
        "environment": ["swamp"],
        "traits": [
            {"name": "Amphibious", "desc": "The dragon can breathe air and water."},
            {"name": "Legendary Resistance (3/Day)", "desc": "If the dragon fails a saving throw, it can choose to succeed instead."},
        ],
        "actions": [
            {"name": "Multiattack", "desc": "The dragon can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws."},
            {"name": "Bite", "desc": "Melee Weapon Attack: +11 to hit, reach 10 ft., one target. Hit: 17 (2d10 + 6) piercing damage plus 4 (1d8) acid damage."},
            {"name": "Claw", "desc": "Melee Weapon Attack: +11 to hit, reach 5 ft., one target. Hit: 13 (2d6 + 6) slashing damage."},
            {"name": "Tail", "desc": "Melee Weapon Attack: +11 to hit, reach 15 ft., one target. Hit: 15 (2d8 + 6) bludgeoning damage."},
            {"name": "Frightful Presence", "desc": "Each creature of the dragon's choice within 120 ft. and aware of it must succeed on a DC 16 Wisdom saving throw or become frightened for 1 minute."},
            {"name": "Acid Breath (Recharge 5-6)", "desc": "The dragon exhales acid in a 60-foot line that is 5 feet wide. Each creature in that line must make a DC 18 Dexterity saving throw, taking 54 (12d8) acid damage on a failed save, or half as much damage on a successful one."},
        ],
        "legendary_actions": [
            {"name": "Detect", "desc": "The dragon makes a Wisdom (Perception) check."},
            {"name": "Tail Attack", "desc": "The dragon makes a tail attack."},
            {"name": "Wing Attack (Costs 2 Actions)", "desc": "The dragon beats its wings. Each creature within 10 ft. of the dragon must succeed on a DC 19 Dexterity saving throw or take 13 (2d6 + 6) bludgeoning damage and be knocked prone. The dragon can then fly up to half its flying speed."},
        ],
    },
    {
        "name": "Ancient Red Dragon", "type": "dragon", "size": "gargantuan", "alignment": "chaotic evil",
        "cr": 24, "xp": 62000, "ac": 22, "ac_type": "natural armor",
        "hp": "546 (28d20+252)", "hp_avg": 546, "speed": "40 ft., climb 40 ft., fly 80 ft.",
        "str": 30, "dex": 10, "con": 29, "int": 18, "wis": 15, "cha": 23,
        "skills": "Perception +16, Stealth +7", "saves": "Dex +7, Con +16, Wis +9, Cha +13",
        "damage_immunities": "fire",
        "senses": "blindsight 60 ft., darkvision 120 ft., passive Perception 26",
        "languages": "Common, Draconic",
        "environment": ["mountain"],
        "traits": [{"name": "Legendary Resistance (3/Day)", "desc": "If the dragon fails a saving throw, it can choose to succeed instead."}],
        "actions": [
            {"name": "Multiattack", "desc": "The dragon can use its Frightful Presence. It then makes three attacks: one with its bite and two with its claws."},
            {"name": "Bite", "desc": "Melee Weapon Attack: +17 to hit, reach 15 ft., one target. Hit: 21 (2d10 + 10) piercing damage plus 14 (4d6) fire damage."},
            {"name": "Claw", "desc": "Melee Weapon Attack: +17 to hit, reach 10 ft., one target. Hit: 17 (2d6 + 10) slashing damage."},
            {"name": "Tail", "desc": "Melee Weapon Attack: +17 to hit, reach 20 ft., one target. Hit: 19 (2d8 + 10) bludgeoning damage."},
            {"name": "Frightful Presence", "desc": "Each creature of the dragon's choice within 120 ft. and aware of it must succeed on a DC 21 Wisdom saving throw or become frightened for 1 minute."},
            {"name": "Fire Breath (Recharge 5-6)", "desc": "The dragon exhales fire in a 90-foot cone. Each creature in that area must make a DC 24 Dexterity saving throw, taking 91 (26d6) fire damage on a failed save, or half as much damage on a successful one."},
        ],
        "legendary_actions": [
            {"name": "Detect", "desc": "The dragon makes a Wisdom (Perception) check."},
            {"name": "Tail Attack", "desc": "The dragon makes a tail attack."},
            {"name": "Wing Attack (Costs 2 Actions)", "desc": "The dragon beats its wings. Each creature within 15 ft. of the dragon must succeed on a DC 25 Dexterity saving throw or take 17 (2d6 + 10) bludgeoning damage and be knocked prone. The dragon can then fly up to half its flying speed."},
        ],
    },
    {
        "name": "Werewolf", "type": "humanoid", "size": "medium", "alignment": "chaotic evil",
        "cr": 3, "xp": 700, "ac": 11, "ac_type": "natural armor in humanoid form, 12 in wolf or hybrid form",
        "hp": "58 (9d8+18)", "hp_avg": 58, "speed": "30 ft. (40 ft. in wolf form)",
        "str": 15, "dex": 13, "con": 14, "int": 10, "wis": 11, "cha": 10,
        "skills": "Perception +4, Stealth +3", "saves": None,
        "damage_immunities": "bludgeoning, piercing, and slashing from nonmagical attacks not made with silvered weapons",
        "senses": "passive Perception 14",
        "languages": "Common (can't speak in wolf form)",
        "environment": ["forest", "grassland"],
        "traits": [
            {"name": "Shapechanger", "desc": "The werewolf can use its action to polymorph into a wolf-humanoid hybrid or into a wolf, or back into its true form, which is humanoid."},
            {"name": "Keen Hearing and Smell", "desc": "The werewolf has advantage on Wisdom (Perception) checks that rely on hearing or smell."},
        ],
        "actions": [
            {"name": "Multiattack (Humanoid or Hybrid Form Only)", "desc": "The werewolf makes two attacks: one with its bite and one with its claws or spear."},
            {"name": "Bite (Wolf or Hybrid Form Only)", "desc": "Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 6 (1d8 + 2) piercing damage. If the target is a humanoid, it must succeed on a DC 12 Constitution saving throw or be cursed with werewolf lycanthropy."},
            {"name": "Claws (Hybrid Form Only)", "desc": "Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 7 (2d4 + 2) slashing damage."},
            {"name": "Spear (Humanoid Form Only)", "desc": "Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 20/60 ft., one creature. Hit: 5 (1d6 + 2) piercing damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Vampire Spawn", "type": "undead", "size": "medium", "alignment": "neutral evil",
        "cr": 5, "xp": 1800, "ac": 15, "ac_type": "natural armor",
        "hp": "82 (11d8+33)", "hp_avg": 82, "speed": "30 ft.",
        "str": 16, "dex": 16, "con": 16, "int": 11, "wis": 10, "cha": 12,
        "skills": "Perception +3, Stealth +6", "saves": "Dex +6, Wis +3",
        "damage_resistances": "necrotic; bludgeoning, piercing, and slashing from nonmagical attacks",
        "senses": "darkvision 60 ft., passive Perception 13",
        "languages": "the languages it knew in life",
        "environment": ["underdark", "urban"],
        "traits": [
            {"name": "Regeneration", "desc": "The vampire regains 10 hit points at the start of its turn if it has at least 1 hit point and isn't in sunlight or running water. If the vampire takes radiant damage or damage from holy water, this trait doesn't function at the start of the vampire's next turn."},
            {"name": "Spider Climb", "desc": "The vampire can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check."},
            {"name": "Vampire Weaknesses", "desc": "The vampire has the following flaws: Forbiddance, Harmed by Running Water, Stake to the Heart, Sunlight Hypersensitivity."},
        ],
        "actions": [
            {"name": "Multiattack", "desc": "The vampire makes two attacks, only one of which can be a bite attack."},
            {"name": "Bite", "desc": "Melee Weapon Attack: +6 to hit, reach 5 ft., one willing creature, or a creature that is grappled by the vampire, incapacitated, or restrained. Hit: 6 (1d6 + 3) piercing damage plus 7 (2d6) necrotic damage."},
            {"name": "Claws", "desc": "Melee Weapon Attack: +6 to hit, reach 5 ft., one creature. Hit: 8 (2d4 + 3) slashing damage. Instead of dealing damage, the vampire can grapple the target (escape DC 13)."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Lich", "type": "undead", "size": "medium", "alignment": "any evil",
        "cr": 21, "xp": 33000, "ac": 17, "ac_type": "natural armor",
        "hp": "135 (18d8+54)", "hp_avg": 135, "speed": "30 ft.",
        "str": 11, "dex": 16, "con": 16, "int": 20, "wis": 14, "cha": 16,
        "skills": "Arcana +19, History +12, Insight +9, Perception +9",
        "saves": "Con +10, Int +12, Wis +9",
        "damage_resistances": "cold, lightning, necrotic",
        "damage_immunities": "poison; bludgeoning, piercing, and slashing from nonmagical attacks",
        "condition_immunities": "charmed, exhaustion, frightened, paralyzed, poisoned",
        "senses": "truesight 120 ft., passive Perception 19",
        "languages": "Common plus up to five other languages",
        "environment": ["underdark", "urban"],
        "traits": [
            {"name": "Legendary Resistance (3/Day)", "desc": "If the lich fails a saving throw, it can choose to succeed instead."},
            {"name": "Rejuvenation", "desc": "If it has a phylactery, a destroyed lich gains a new body in 1d10 days, regaining all its hit points and becoming active again."},
            {"name": "Turn Resistance", "desc": "The lich has advantage on saving throws against any effect that turns undead."},
        ],
        "actions": [
            {"name": "Paralyzing Touch", "desc": "Melee Spell Attack: +12 to hit, reach 5 ft., one creature. Hit: 10 (3d6) cold damage. The target must succeed on a DC 18 Constitution saving throw or be paralyzed for 1 minute."},
            {"name": "Spellcasting", "desc": "The lich is an 18th-level spellcaster. Its spellcasting ability is Intelligence (spell save DC 20, +12 to hit with spell attacks). Cantrips: mage hand, prestidigitation, ray of frost. 1st-9th level spells prepared."},
        ],
        "legendary_actions": [
            {"name": "Cantrip", "desc": "The lich casts a cantrip."},
            {"name": "Paralyzing Touch (Costs 2 Actions)", "desc": "The lich uses its Paralyzing Touch."},
            {"name": "Frightening Gaze (Costs 2 Actions)", "desc": "The lich fixes its gaze on one creature it can see within 10 ft. The target must succeed on a DC 18 Wisdom saving throw against this magic or become frightened for 1 minute."},
            {"name": "Disrupt Life (Costs 3 Actions)", "desc": "Each non-undead creature within 20 ft. of the lich must make a DC 18 Constitution saving throw, taking 21 (6d6) necrotic damage on a failed save, or half as much damage on a successful one."},
        ],
    },
    {
        "name": "Beholder", "type": "aberration", "size": "large", "alignment": "lawful evil",
        "cr": 13, "xp": 10000, "ac": 18, "ac_type": "natural armor",
        "hp": "180 (19d10+76)", "hp_avg": 180, "speed": "0 ft., fly 20 ft. (hover)",
        "str": 10, "dex": 14, "con": 18, "int": 17, "wis": 15, "cha": 17,
        "skills": "Perception +12", "saves": "Int +8, Wis +7, Cha +8",
        "condition_immunities": "prone",
        "senses": "darkvision 120 ft., passive Perception 22",
        "languages": "Deep Speech, Undercommon",
        "environment": ["underdark"],
        "traits": [{"name": "Antimagic Cone", "desc": "The beholder's central eye creates an area of antimagic, as in the antimagic field spell, in a 150-foot cone. At the start of each of its turns, the beholder decides which way the cone faces."}],
        "actions": [
            {"name": "Bite", "desc": "Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 14 (4d6) piercing damage."},
            {"name": "Eye Rays", "desc": "The beholder shoots three of the following magical eye rays at random, choosing one to three targets it can see within 120 ft.: Charm Ray, Paralyzing Ray, Fear Ray, Slowing Ray, Enervation Ray, Telekinetic Ray, Sleep Ray, Petrification Ray, Disintegration Ray, Death Ray."},
        ],
        "legendary_actions": [
            {"name": "Eye Ray", "desc": "The beholder uses one random eye ray."},
        ],
    },
    {
        "name": "Mind Flayer", "type": "aberration", "size": "medium", "alignment": "lawful evil",
        "cr": 7, "xp": 2900, "ac": 15, "ac_type": "breastplate",
        "hp": "71 (13d8+13)", "hp_avg": 71, "speed": "30 ft.",
        "str": 11, "dex": 12, "con": 12, "int": 19, "wis": 17, "cha": 17,
        "skills": "Arcana +7, Deception +6, Insight +6, Perception +6, Persuasion +6, Stealth +4",
        "saves": "Int +7, Wis +6, Cha +6",
        "senses": "darkvision 120 ft., passive Perception 16",
        "languages": "Deep Speech, Undercommon, telepathy 120 ft.",
        "environment": ["underdark"],
        "traits": [
            {"name": "Magic Resistance", "desc": "The mind flayer has advantage on saving throws against spells and other magical effects."},
            {"name": "Innate Spellcasting (Psionics)", "desc": "The mind flayer's innate spellcasting ability is Intelligence (spell save DC 15). It can innately cast detect thoughts and levitate at will."},
        ],
        "actions": [
            {"name": "Tentacles", "desc": "Melee Weapon Attack: +7 to hit, reach 5 ft., one creature. Hit: 15 (2d10 + 4) psychic damage. If the target is Medium or smaller, it is grappled (escape DC 15) and must succeed on a DC 15 Intelligence saving throw or be stunned until this grapple ends."},
            {"name": "Extract Brain", "desc": "Melee Weapon Attack: +7 to hit, reach 5 ft., one incapacitated humanoid grappled by the mind flayer. Hit: 55 (10d10) piercing damage. If this reduces the target to 0 hit points, the mind flayer kills the target by extracting and devouring its brain."},
            {"name": "Mind Blast (Recharge 5-6)", "desc": "The mind flayer magically emits psychic energy in a 60-foot cone. Each creature in that area must succeed on a DC 15 Intelligence saving throw or take 22 (4d8 + 4) psychic damage and be stunned for 1 minute."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Rakshasa", "type": "fiend", "size": "medium", "alignment": "lawful evil",
        "cr": 13, "xp": 10000, "ac": 16, "ac_type": "natural armor",
        "hp": "110 (13d8+52)", "hp_avg": 110, "speed": "40 ft.",
        "str": 14, "dex": 17, "con": 18, "int": 13, "wis": 16, "cha": 20,
        "skills": "Deception +10, Insight +8", "saves": None,
        "damage_vulnerabilities": "piercing from magic weapons wielded by good creatures",
        "damage_immunities": "bludgeoning, piercing, and slashing from nonmagical attacks",
        "senses": "darkvision 60 ft., passive Perception 13",
        "languages": "Common, Infernal",
        "environment": ["urban"],
        "traits": [
            {"name": "Limited Magic Immunity", "desc": "The rakshasa can't be affected or detected by spells of 6th level or lower unless it wishes to be. It has advantage on saving throws against all other spells and magical effects."},
            {"name": "Innate Spellcasting", "desc": "The rakshasa's innate spellcasting ability is Charisma (spell save DC 18, +10 to hit with spell attacks). At will: detect thoughts, disguise self, mage hand, minor illusion. 3/day each: charm person, detect magic, invisibility, major image, suggestion. 1/day each: dominate person, fly, plane shift, true seeing."},
        ],
        "actions": [
            {"name": "Multiattack", "desc": "The rakshasa makes two claw attacks."},
            {"name": "Claw", "desc": "Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 9 (2d6 + 2) slashing damage, and the target is cursed if it is a creature. The curse takes effect whenever the target takes a short or long rest, preventing the target from regaining hit points from that rest."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Balor", "type": "fiend", "size": "huge", "alignment": "chaotic evil",
        "cr": 19, "xp": 22000, "ac": 19, "ac_type": "natural armor",
        "hp": "262 (21d12+126)", "hp_avg": 262, "speed": "40 ft., fly 80 ft.",
        "str": 26, "dex": 15, "con": 22, "int": 20, "wis": 16, "cha": 22,
        "skills": None, "saves": "Str +14, Con +12, Wis +9, Cha +12",
        "damage_resistances": "cold, lightning; bludgeoning, piercing, and slashing from nonmagical attacks",
        "damage_immunities": "fire, poison",
        "condition_immunities": "poisoned",
        "senses": "truesight 120 ft., passive Perception 13",
        "languages": "Abyssal, telepathy 120 ft.",
        "environment": ["underdark", "mountain"],
        "traits": [
            {"name": "Death Throes", "desc": "When the balor dies, it explodes, and each creature within 30 ft. of it must make a DC 20 Dexterity saving throw, taking 70 (20d6) fire damage on a failed save, or half as much damage on a successful one."},
            {"name": "Fire Aura", "desc": "At the start of each of the balor's turns, each creature within 5 ft. of it takes 10 (3d6) fire damage, and flammable objects in the aura ignite."},
            {"name": "Magic Resistance", "desc": "The balor has advantage on saving throws against spells and other magical effects."},
            {"name": "Magic Weapons", "desc": "The balor's weapon attacks are magical."},
        ],
        "actions": [
            {"name": "Multiattack", "desc": "The balor makes two attacks: one with its longsword and one with its whip."},
            {"name": "Longsword", "desc": "Melee Weapon Attack: +14 to hit, reach 10 ft., one target. Hit: 21 (3d8 + 8) slashing damage plus 13 (3d8) lightning damage. If the balor scores a critical hit, it rolls damage dice three times, instead of twice."},
            {"name": "Whip", "desc": "Melee Weapon Attack: +14 to hit, reach 30 ft., one target. Hit: 15 (2d6 + 8) slashing damage plus 10 (3d6) fire damage, and the target must succeed on a DC 20 Strength saving throw or be pulled up to 25 ft. toward the balor."},
            {"name": "Teleport", "desc": "The balor magically teleports, along with any equipment it is wearing or carrying, up to 120 ft. to an unoccupied space it can see."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Pit Fiend", "type": "fiend", "size": "large", "alignment": "lawful evil",
        "cr": 20, "xp": 25000, "ac": 19, "ac_type": "natural armor",
        "hp": "300 (24d10+168)", "hp_avg": 300, "speed": "30 ft., fly 60 ft.",
        "str": 26, "dex": 14, "con": 24, "int": 22, "wis": 18, "cha": 24,
        "skills": None, "saves": "Dex +8, Con +13, Wis +10",
        "damage_resistances": "cold; bludgeoning, piercing, and slashing from nonmagical attacks",
        "damage_immunities": "fire, poison",
        "condition_immunities": "poisoned",
        "senses": "truesight 120 ft., passive Perception 14",
        "languages": "Infernal, telepathy 120 ft.",
        "environment": ["underdark", "mountain"],
        "traits": [
            {"name": "Fear Aura", "desc": "Any creature hostile to the pit fiend that starts its turn within 20 ft. of the pit fiend must make a DC 21 Wisdom saving throw, unless the pit fiend is incapacitated. On a failed save, the creature is frightened until the start of its next turn."},
            {"name": "Magic Resistance", "desc": "The pit fiend has advantage on saving throws against spells and other magical effects."},
            {"name": "Magic Weapons", "desc": "The pit fiend's weapon attacks are magical."},
            {"name": "Innate Spellcasting", "desc": "The pit fiend's spellcasting ability is Charisma (spell save DC 21). At will: detect magic, fireball. 3/day each: hold monster, wall of fire."},
        ],
        "actions": [
            {"name": "Multiattack", "desc": "The pit fiend makes four attacks: one with its bite, one with its claw, one with its mace, and one with its tail."},
            {"name": "Bite", "desc": "Melee Weapon Attack: +14 to hit, reach 5 ft., one target. Hit: 22 (4d6 + 8) piercing damage. The target must succeed on a DC 21 Constitution saving throw or become poisoned."},
            {"name": "Claw", "desc": "Melee Weapon Attack: +14 to hit, reach 10 ft., one target. Hit: 17 (2d8 + 8) slashing damage."},
            {"name": "Mace", "desc": "Melee Weapon Attack: +14 to hit, reach 10 ft., one target. Hit: 15 (2d6 + 8) bludgeoning damage plus 21 (6d6) fire damage."},
            {"name": "Tail", "desc": "Melee Weapon Attack: +14 to hit, reach 10 ft., one target. Hit: 24 (3d10 + 8) bludgeoning damage."},
        ],
        "legendary_actions": [],
    },
    {
        "name": "Solar", "type": "celestial", "size": "large", "alignment": "lawful good",
        "cr": 21, "xp": 33000, "ac": 21, "ac_type": "natural armor",
        "hp": "243 (18d10+144)", "hp_avg": 243, "speed": "50 ft., fly 150 ft.",
        "str": 26, "dex": 22, "con": 26, "int": 25, "wis": 25, "cha": 30,
        "skills": "Perception +14", "saves": "Int +14, Wis +14, Cha +17",
        "damage_resistances": "radiant; bludgeoning, piercing, and slashing from nonmagical attacks",
        "damage_immunities": "necrotic, poison",
        "condition_immunities": "charmed, exhaustion, frightened, poisoned",
        "senses": "truesight 120 ft., passive Perception 24",
        "languages": "all, telepathy 120 ft.",
        "environment": ["mountain"],
        "traits": [
            {"name": "Angelic Weapons", "desc": "The solar's weapon attacks are magical. When the solar hits with any weapon, the weapon deals an extra 6d8 radiant damage (included in the attack)."},
            {"name": "Divine Awareness", "desc": "The solar knows if it hears a lie."},
            {"name": "Magic Resistance", "desc": "The solar has advantage on saving throws against spells and other magical effects."},
            {"name": "Innate Spellcasting", "desc": "The solar's spellcasting ability is Charisma (spell save DC 25). At will: detect evil and good, invisibility (self only). 3/day each: blade barrier, dispel evil and good, resurrection. 1/day each: commune, control weather."},
        ],
        "actions": [
            {"name": "Multiattack", "desc": "The solar makes two greatsword attacks."},
            {"name": "Greatsword", "desc": "Melee Weapon Attack: +15 to hit, reach 5 ft., one target. Hit: 22 (4d6 + 8) slashing damage plus 27 (6d8) radiant damage."},
            {"name": "Slaying Longbow", "desc": "Ranged Weapon Attack: +13 to hit, range 150/600 ft., one target. Hit: 15 (2d8 + 6) piercing damage plus 27 (6d8) radiant damage. If the target has 100 hit points or fewer, it must succeed on a DC 15 Constitution saving throw or die."},
            {"name": "Flying Sword", "desc": "The solar releases its greatsword to hover magically in an unoccupied space within 5 ft. of it. The sword then makes one greatsword attack against a target, then returns to the solar."},
            {"name": "Healing Touch (4/Day)", "desc": "The solar touches another creature. The target magically regains 40 (8d8 + 4) hit points and is freed from any curse, disease, poison, blindness, or deafness."},
        ],
        "legendary_actions": [
            {"name": "Teleport", "desc": "The solar magically teleports, along with any equipment it is wearing or carrying, up to 120 ft. to an unoccupied space it can see."},
            {"name": "Searing Burst (Costs 2 Actions)", "desc": "The solar emits magical, divine energy. Each creature of its choice in a 10-foot radius must make a DC 23 Dexterity saving throw, taking 14 (4d6) fire damage plus 14 (4d6) radiant damage on a failed save, or half as much damage on a successful one."},
            {"name": "Blinding Gaze (Costs 3 Actions)", "desc": "The solar targets one creature it can see within 30 ft. If the target can see it, the target must succeed on a DC 15 Constitution saving throw or be blinded until magic such as the lesser restoration spell removes the blindness."},
        ],
    },
    {
        "name": "Tarrasque", "type": "monstrosity", "size": "gargantuan", "alignment": "unaligned",
        "cr": 30, "xp": 155000, "ac": 25, "ac_type": "natural armor",
        "hp": "676 (33d20+330)", "hp_avg": 676, "speed": "40 ft.",
        "str": 30, "dex": 11, "con": 30, "int": 3, "wis": 11, "cha": 11,
        "skills": None, "saves": "Int +5, Wis +9, Cha +9",
        "damage_immunities": "fire, poison; bludgeoning, piercing, and slashing from nonmagical attacks",
        "condition_immunities": "charmed, frightened, paralyzed, poisoned",
        "senses": "blindsight 120 ft., passive Perception 10",
        "languages": "—",
        "environment": ["grassland", "mountain"],
        "traits": [
            {"name": "Legendary Resistance (3/Day)", "desc": "If the tarrasque fails a saving throw, it can choose to succeed instead."},
            {"name": "Magic Resistance", "desc": "The tarrasque has advantage on saving throws against spells and other magical effects."},
            {"name": "Reflective Carapace", "desc": "Any time the tarrasque is targeted by a magic missile spell, a line spell, or a spell that requires a ranged attack roll, roll a d6. On a 1 to 5, the tarrasque is unaffected. On a 6, the tarrasque is unaffected, and the effect is reflected back at the caster."},
            {"name": "Siege Monster", "desc": "The tarrasque deals double damage to objects and structures."},
        ],
        "actions": [
            {"name": "Multiattack", "desc": "The tarrasque can use its Frightful Presence. It then makes five attacks: one with its bite, two with its claws, one with its horns, and one with its tail."},
            {"name": "Bite", "desc": "Melee Weapon Attack: +19 to hit, reach 10 ft., one target. Hit: 36 (4d12 + 10) piercing damage. If the target is a creature, it is grappled (escape DC 20)."},
            {"name": "Claw", "desc": "Melee Weapon Attack: +19 to hit, reach 15 ft., one target. Hit: 28 (4d8 + 10) slashing damage."},
            {"name": "Horns", "desc": "Melee Weapon Attack: +19 to hit, reach 10 ft., one target. Hit: 32 (4d10 + 10) piercing damage."},
            {"name": "Tail", "desc": "Melee Weapon Attack: +19 to hit, reach 20 ft., one target. Hit: 24 (4d6 + 10) bludgeoning damage."},
            {"name": "Frightful Presence", "desc": "Each creature of the tarrasque's choice within 120 ft. of it and aware of it must succeed on a DC 17 Wisdom saving throw or become frightened for 1 minute."},
            {"name": "Swallow", "desc": "The tarrasque makes one bite attack against a Large or smaller creature it is grappling. If the attack hits, the target takes the bite's damage, is swallowed, and the grapple ends."},
        ],
        "legendary_actions": [
            {"name": "Attack", "desc": "The tarrasque makes one claw attack or tail attack."},
            {"name": "Move", "desc": "The tarrasque moves up to half its speed."},
            {"name": "Chomp (Costs 2 Actions)", "desc": "The tarrasque makes one bite attack or uses its Swallow."},
        ],
    },
    # ── Quick additions (brief data) ────────────────────────────────────────
    {"name": "Goblin Boss","type":"humanoid","size":"small","alignment":"neutral evil","cr":1,"xp":200,"ac":17,"ac_type":"chain shirt, shield","hp":"21 (6d6)","hp_avg":21,"speed":"30 ft.","str":10,"dex":14,"con":10,"int":10,"wis":8,"cha":10,"skills":"Stealth +6","saves":None,"senses":"darkvision 60 ft., passive Perception 9","languages":"Common, Goblin","environment":["forest","underdark"],"traits":[{"name":"Nimble Escape","desc":"The goblin can take the Disengage or Hide action as a bonus action on each of its turns."}],"actions":[{"name":"Multiattack","desc":"The goblin makes two attacks with its scimitar."},{"name":"Scimitar","desc":"Melee Weapon Attack: +4 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) slashing damage."},{"name":"Javelin","desc":"Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 30/120 ft., one target. Hit: 5 (1d6 + 2) piercing damage."},{"name":"Redirect Attack","desc":"When a creature the goblin boss can see targets it with an attack, the boss chooses another goblin within 5 ft. of it. The two goblins swap places, and the chosen goblin becomes the target instead."}],"legendary_actions":[]},
    {"name": "Bandit","type":"humanoid","size":"medium","alignment":"any non-lawful","cr":0.125,"xp":25,"ac":12,"ac_type":"leather armor","hp":"11 (2d8+2)","hp_avg":11,"speed":"30 ft.","str":11,"dex":12,"con":12,"int":10,"wis":10,"cha":10,"skills":None,"saves":None,"senses":"passive Perception 10","languages":"any one language (usually Common)","environment":["forest","grassland","urban"],"traits":[],"actions":[{"name":"Scimitar","desc":"Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6 + 1) slashing damage."},{"name":"Light Crossbow","desc":"Ranged Weapon Attack: +3 to hit, range 80/320 ft., one target. Hit: 5 (1d8 + 1) piercing damage."}],"legendary_actions":[]},
    {"name": "Cultist","type":"humanoid","size":"medium","alignment":"any non-good","cr":0.125,"xp":25,"ac":12,"ac_type":"leather armor","hp":"9 (2d8)","hp_avg":9,"speed":"30 ft.","str":11,"dex":12,"con":10,"int":10,"wis":11,"cha":10,"skills":"Deception +2, Religion +2","saves":None,"senses":"passive Perception 10","languages":"any one language (usually Common)","environment":["urban","underdark"],"traits":[{"name":"Dark Devotion","desc":"The cultist has advantage on saving throws against being charmed or frightened."}],"actions":[{"name":"Scimitar","desc":"Melee Weapon Attack: +3 to hit, reach 5 ft., one creature. Hit: 4 (1d6 + 1) slashing damage."}],"legendary_actions":[]},
    {"name": "Guard","type":"humanoid","size":"medium","alignment":"any","cr":0.125,"xp":25,"ac":16,"ac_type":"chain shirt, shield","hp":"11 (2d8+2)","hp_avg":11,"speed":"30 ft.","str":13,"dex":12,"con":12,"int":10,"wis":11,"cha":10,"skills":"Perception +2","saves":None,"senses":"passive Perception 12","languages":"any one language (usually Common)","environment":["urban"],"traits":[],"actions":[{"name":"Spear","desc":"Melee or Ranged Weapon Attack: +3 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d6 + 1) piercing damage."}],"legendary_actions":[]},
    {"name": "Thug","type":"humanoid","size":"medium","alignment":"any non-good","cr":0.5,"xp":100,"ac":11,"ac_type":"leather armor","hp":"32 (5d8+10)","hp_avg":32,"speed":"30 ft.","str":15,"dex":11,"con":14,"int":10,"wis":10,"cha":11,"skills":"Intimidation +2","saves":None,"senses":"passive Perception 10","languages":"any one language (usually Common)","environment":["urban"],"traits":[{"name":"Pack Tactics","desc":"The thug has advantage on an attack roll against a creature if at least one of the thug's allies is within 5 ft. of the creature and the ally isn't incapacitated."}],"actions":[{"name":"Multiattack","desc":"The thug makes two melee attacks."},{"name":"Mace","desc":"Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 5 (1d6 + 2) bludgeoning damage."},{"name":"Heavy Crossbow","desc":"Ranged Weapon Attack: +2 to hit, range 100/400 ft., one target. Hit: 5 (1d10) piercing damage."}],"legendary_actions":[]},
    {"name": "Assassin","type":"humanoid","size":"medium","alignment":"any non-good","cr":8,"xp":3900,"ac":15,"ac_type":"studded leather","hp":"78 (12d8+24)","hp_avg":78,"speed":"30 ft.","str":11,"dex":16,"con":14,"int":13,"wis":11,"cha":10,"skills":"Acrobatics +6, Deception +3, Perception +3, Stealth +9","saves":"Dex +6, Int +4","damage_resistances":"poison","senses":"passive Perception 13","languages":"Thieves' cant plus any two languages","environment":["urban"],"traits":[{"name":"Assassinate","desc":"During its first turn, the assassin has advantage on attack rolls against any creature that hasn't taken a turn. Any hit the assassin scores against a surprised creature is a critical hit."},{"name":"Evasion","desc":"If the assassin is subjected to an effect that allows a Dexterity saving throw to take only half damage, the assassin instead takes no damage if it succeeds on the saving throw, and only half damage if it fails."},{"name":"Sneak Attack","desc":"Once per turn, the assassin deals an extra 14 (4d6) damage when it hits a target with a weapon attack and has advantage on the attack roll."}],"actions":[{"name":"Multiattack","desc":"The assassin makes two shortsword attacks."},{"name":"Shortsword","desc":"Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) piercing damage, and the target must make a DC 15 Constitution saving throw, taking 24 (7d6) poison damage on a failed save, or half as much damage on a successful one."},{"name":"Light Crossbow","desc":"Ranged Weapon Attack: +6 to hit, range 80/320 ft., one target. Hit: 7 (1d8 + 3) piercing damage."}],"legendary_actions":[]},
    {"name": "Archmage","type":"humanoid","size":"medium","alignment":"any","cr":12,"xp":8400,"ac":12,"ac_type":"robe of the archmagi (15 with mage armor)","hp":"99 (18d8+18)","hp_avg":99,"speed":"30 ft.","str":10,"dex":14,"con":12,"int":20,"wis":15,"cha":16,"skills":"Arcana +13, History +13","saves":"Int +9, Wis +6","damage_resistances":"damage from spells; nonmagical bludgeoning, piercing, and slashing","senses":"passive Perception 12","languages":"any six languages","environment":["urban"],"traits":[{"name":"Magic Resistance","desc":"The archmage has advantage on saving throws against spells and other magical effects."},{"name":"Spellcasting","desc":"The archmage is an 18th-level spellcaster. Its spellcasting ability is Intelligence (spell save DC 17, +9 to hit with spell attacks). Cantrips: fire bolt, light, mage hand, prestidigitation, shocking grasp. 1st-9th level spells prepared."}],"actions":[{"name":"Dagger","desc":"Melee or Ranged Weapon Attack: +6 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d4 + 2) piercing damage."}],"legendary_actions":[]},
    {"name": "Mage","type":"humanoid","size":"medium","alignment":"any","cr":6,"xp":2300,"ac":12,"ac_type":"15 with mage armor","hp":"40 (9d8)","hp_avg":40,"speed":"30 ft.","str":9,"dex":14,"con":11,"int":17,"wis":12,"cha":11,"skills":"Arcana +6, History +6","saves":"Int +6, Wis +4","senses":"passive Perception 11","languages":"any four languages","environment":["urban"],"traits":[{"name":"Spellcasting","desc":"The mage is a 9th-level spellcaster. Spell save DC 14, +6 to hit. Cantrips: fire bolt, light, mage hand, prestidigitation. 1st-5th level spells prepared."}],"actions":[{"name":"Dagger","desc":"Melee or Ranged Weapon Attack: +5 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 4 (1d4 + 2) piercing damage."}],"legendary_actions":[]},
    {"name": "Priest","type":"humanoid","size":"medium","alignment":"any","cr":2,"xp":450,"ac":13,"ac_type":"chain shirt","hp":"27 (5d8+5)","hp_avg":27,"speed":"30 ft.","str":10,"dex":10,"con":12,"int":13,"wis":16,"cha":13,"skills":"Medicine +7, Persuasion +3, Religion +5","saves":None,"senses":"passive Perception 13","languages":"any two languages","environment":["urban"],"traits":[{"name":"Divine Eminence","desc":"As a bonus action, the priest can expend a spell slot to cause its melee weapon attacks to magically deal an extra 10 (3d6) radiant damage to a target on a hit."},{"name":"Spellcasting","desc":"The priest is a 5th-level spellcaster. Spell save DC 13, +5 to hit. Cantrips: light, sacred flame, thaumaturgy. 1st-3rd level spells prepared."}],"actions":[{"name":"Mace","desc":"Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 3 (1d6) bludgeoning damage."}],"legendary_actions":[]},
    {"name": "Knight","type":"humanoid","size":"medium","alignment":"any","cr":3,"xp":700,"ac":18,"ac_type":"plate","hp":"52 (8d8+16)","hp_avg":52,"speed":"30 ft.","str":16,"dex":11,"con":14,"int":11,"wis":11,"cha":15,"skills":None,"saves":"Con +4, Wis +2","senses":"passive Perception 10","languages":"any one language (usually Common)","environment":["urban","grassland"],"traits":[{"name":"Brave","desc":"The knight has advantage on saving throws against being frightened."}],"actions":[{"name":"Multiattack","desc":"The knight makes two melee attacks."},{"name":"Greatsword","desc":"Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) slashing damage."},{"name":"Heavy Crossbow","desc":"Ranged Weapon Attack: +2 to hit, range 100/400 ft., one target. Hit: 5 (1d10) piercing damage."},{"name":"Leadership (Recharges after a Short or Long Rest)","desc":"For 1 minute, the knight can utter a special command or warning whenever a nonhostile creature that it can see within 30 ft. makes an attack roll or a saving throw."}],"legendary_actions":[]},
    {"name": "Shadow","type":"undead","size":"medium","alignment":"chaotic evil","cr":0.5,"xp":100,"ac":12,"ac_type":None,"hp":"16 (3d8+3)","hp_avg":16,"speed":"40 ft.","str":6,"dex":14,"con":13,"int":6,"wis":10,"cha":8,"skills":"Stealth +4","saves":None,"damage_vulnerabilities":"radiant","damage_resistances":"acid, cold, fire, lightning, thunder; bludgeoning, piercing, and slashing from nonmagical attacks","damage_immunities":"necrotic, poison","condition_immunities":"exhaustion, frightened, grappled, paralyzed, petrified, poisoned, prone, restrained","senses":"darkvision 60 ft., passive Perception 10","languages":"—","environment":["underdark","urban"],"traits":[{"name":"Amorphous","desc":"The shadow can move through a space as narrow as 1 inch wide without squeezing."},{"name":"Shadow Stealth","desc":"While in dim light or darkness, the shadow can take the Hide action as a bonus action."},{"name":"Sunlight Weakness","desc":"While in sunlight, the shadow has disadvantage on attack rolls, ability checks, and saving throws."}],"actions":[{"name":"Strength Drain","desc":"Melee Weapon Attack: +4 to hit, reach 5 ft., one creature. Hit: 9 (2d6 + 2) necrotic damage, and the target's Strength score is reduced by 1d4. The target dies if this reduces its Strength to 0."}],"legendary_actions":[]},
    {"name": "Wraith","type":"undead","size":"medium","alignment":"neutral evil","cr":5,"xp":1800,"ac":13,"ac_type":None,"hp":"67 (9d8+27)","hp_avg":67,"speed":"0 ft., fly 60 ft. (hover)","str":6,"dex":16,"con":16,"int":12,"wis":14,"cha":15,"skills":None,"saves":None,"damage_resistances":"acid, cold, fire, lightning, thunder; bludgeoning, piercing, and slashing from nonmagical attacks not made with silvered weapons","damage_immunities":"necrotic, poison","condition_immunities":"charmed, exhaustion, grappled, paralyzed, petrified, poisoned, prone, restrained","senses":"darkvision 60 ft., passive Perception 12","languages":"the languages it knew in life","environment":["underdark","urban"],"traits":[{"name":"Incorporeal Movement","desc":"The wraith can move through other creatures and objects as if they were difficult terrain."},{"name":"Sunlight Sensitivity","desc":"While in sunlight, the wraith has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight."}],"actions":[{"name":"Life Drain","desc":"Melee Weapon Attack: +6 to hit, reach 5 ft., one creature. Hit: 21 (4d8 + 3) necrotic damage. The target must succeed on a DC 14 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken."},{"name":"Create Specter","desc":"The wraith targets a humanoid within 10 ft. of it that has been dead for no longer than 1 minute and died violently. The target's spirit rises as a specter under the wraith's control."}],"legendary_actions":[]},
    {"name": "Specter","type":"undead","size":"medium","alignment":"chaotic evil","cr":1,"xp":200,"ac":12,"ac_type":None,"hp":"22 (5d8)","hp_avg":22,"speed":"0 ft., fly 50 ft. (hover)","str":1,"dex":14,"con":11,"int":10,"wis":10,"cha":11,"skills":None,"saves":None,"damage_resistances":"acid, cold, fire, lightning, thunder; bludgeoning, piercing, and slashing from nonmagical attacks","damage_immunities":"necrotic, poison","condition_immunities":"charmed, exhaustion, grappled, paralyzed, petrified, poisoned, prone, restrained, unconscious","senses":"darkvision 60 ft., passive Perception 10","languages":"understands all languages it knew in life but can't speak","environment":["underdark","urban"],"traits":[{"name":"Incorporeal Movement","desc":"The specter can move through other creatures and objects as if they were difficult terrain."},{"name":"Sunlight Sensitivity","desc":"While in sunlight, the specter has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight."}],"actions":[{"name":"Life Drain","desc":"Melee Spell Attack: +4 to hit, reach 5 ft., one creature. Hit: 10 (3d6) necrotic damage. The target must succeed on a DC 10 Constitution saving throw or its hit point maximum is reduced by an amount equal to the damage taken."}],"legendary_actions":[]},
    {"name": "Ghost","type":"undead","size":"medium","alignment":"any","cr":4,"xp":1100,"ac":11,"ac_type":None,"hp":"45 (10d8)","hp_avg":45,"speed":"0 ft., fly 40 ft. (hover)","str":7,"dex":13,"con":10,"int":10,"wis":12,"cha":17,"skills":None,"saves":None,"damage_resistances":"acid, fire, lightning, thunder; bludgeoning, piercing, and slashing from nonmagical attacks","damage_immunities":"cold, necrotic, poison","condition_immunities":"charmed, exhaustion, frightened, grappled, paralyzed, petrified, poisoned, prone, restrained","senses":"darkvision 60 ft., passive Perception 11","languages":"any languages it knew in life","environment":["underdark","urban"],"traits":[{"name":"Ethereal Sight","desc":"The ghost can see 60 ft. into the Ethereal Plane when it is on the Material Plane, and vice versa."},{"name":"Incorporeal Movement","desc":"The ghost can move through other creatures and objects as if they were difficult terrain."}],"actions":[{"name":"Withering Touch","desc":"Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 17 (4d6 + 3) necrotic damage."},{"name":"Etherealness","desc":"The ghost enters the Ethereal Plane from the Material Plane, or vice versa."},{"name":"Horrifying Visage","desc":"Each non-undead creature within 60 ft. of the ghost that can see it must succeed on a DC 13 Wisdom saving throw or be frightened for 1 minute."},{"name":"Possession (Recharge 6)","desc":"One humanoid that the ghost can see within 5 ft. of it must succeed on a DC 13 Charisma saving throw or be possessed by the ghost."}],"legendary_actions":[]},
    {"name": "Mummy","type":"undead","size":"medium","alignment":"lawful evil","cr":3,"xp":700,"ac":11,"ac_type":"natural armor","hp":"58 (9d8+18)","hp_avg":58,"speed":"20 ft.","str":16,"dex":8,"con":15,"int":6,"wis":10,"cha":12,"skills":None,"saves":"Wis +2","damage_vulnerabilities":"fire","damage_resistances":"bludgeoning, piercing, and slashing from nonmagical attacks","damage_immunities":"necrotic, poison","condition_immunities":"charmed, exhaustion, frightened, paralyzed, poisoned","senses":"darkvision 60 ft., passive Perception 10","languages":"the languages it knew in life","environment":["desert","underdark"],"traits":[],"actions":[{"name":"Multiattack","desc":"The mummy can use its Dreadful Glare and makes one attack with its rotting fist."},{"name":"Rotting Fist","desc":"Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) bludgeoning damage plus 10 (3d6) necrotic damage. If the target is a creature, it must succeed on a DC 12 Constitution saving throw or be cursed with mummy rot."},{"name":"Dreadful Glare","desc":"The mummy targets one creature it can see within 60 ft. of it. If the target can see the mummy, it must succeed on a DC 11 Wisdom saving throw against this magic or become frightened until the end of the mummy's next turn."}],"legendary_actions":[]},
    {"name": "Banshee","type":"undead","size":"medium","alignment":"chaotic evil","cr":4,"xp":1100,"ac":12,"ac_type":None,"hp":"58 (13d8)","hp_avg":58,"speed":"0 ft., fly 40 ft. (hover)","str":1,"dex":14,"con":10,"int":12,"wis":11,"cha":17,"skills":None,"saves":"Wis +2, Cha +5","damage_resistances":"acid, fire, lightning, thunder; bludgeoning, piercing, and slashing from nonmagical attacks","damage_immunities":"cold, necrotic, poison","condition_immunities":"charmed, exhaustion, frightened, grappled, paralyzed, petrified, poisoned, prone, restrained","senses":"darkvision 60 ft., passive Perception 10","languages":"Common, Elvish","environment":["forest","swamp","urban"],"traits":[{"name":"Detect Life","desc":"The banshee can magically sense the presence of creatures up to 5 miles away."},{"name":"Incorporeal Movement","desc":"The banshee can move through other creatures and objects as if they were difficult terrain."}],"actions":[{"name":"Corrupting Touch","desc":"Melee Spell Attack: +4 to hit, reach 5 ft., one target. Hit: 12 (3d6 + 2) necrotic damage."},{"name":"Horrifying Visage","desc":"Each non-undead creature within 60 ft. of the banshee that can see it must succeed on a DC 13 Wisdom saving throw or be frightened for 1 minute."},{"name":"Wail (1/Day)","desc":"The banshee releases a mournful wail. All creatures within 30 ft. that can hear must make a DC 13 Constitution saving throw. On a failure, a creature drops to 0 hit points. On a success, a creature takes 10 (3d6) psychic damage."}],"legendary_actions":[]},
    {"name": "Death Knight","type":"undead","size":"medium","alignment":"chaotic evil","cr":17,"xp":18000,"ac":20,"ac_type":"plate, shield","hp":"180 (19d8+95)","hp_avg":180,"speed":"30 ft.","str":20,"dex":11,"con":20,"int":12,"wis":16,"cha":18,"skills":None,"saves":"Dex +6, Wis +9, Cha +10","damage_immunities":"necrotic, poison","condition_immunities":"exhaustion, frightened, poisoned","senses":"darkvision 120 ft., passive Perception 13","languages":"Abyssal, Common","environment":["underdark","mountain"],"traits":[{"name":"Magic Resistance","desc":"The death knight has advantage on saving throws against spells and other magical effects."},{"name":"Marshal Undead","desc":"Undead creatures of the death knight's choice within 60 ft. have advantage on saving throws against features that turn undead."},{"name":"Spellcasting","desc":"The death knight is a 19th-level spellcaster. Spell save DC 18, +10 to hit. 1st-5th level spells prepared."}],"actions":[{"name":"Multiattack","desc":"The death knight makes three longsword attacks."},{"name":"Longsword","desc":"Melee Weapon Attack: +11 to hit, reach 5 ft., one target. Hit: 9 (1d8 + 5) slashing damage, or 10 (1d10 + 5) slashing damage if used with two hands, plus 18 (4d8) necrotic damage."},{"name":"Hellfire Orb (1/Day)","desc":"The death knight hurls a magical ball of fire that explodes at a point it can see within 120 ft. Each creature in a 20-foot-radius sphere must make a DC 18 Dexterity saving throw, taking 35 (10d6) fire damage and 35 (10d6) necrotic damage on a failed save, or half as much on a success."}],"legendary_actions":[]},
    {"name": "Dragon Turtle","type":"dragon","size":"gargantuan","alignment":"neutral","cr":17,"xp":18000,"ac":20,"ac_type":"natural armor","hp":"341 (22d20+110)","hp_avg":341,"speed":"20 ft., swim 40 ft.","str":25,"dex":10,"con":20,"int":10,"wis":12,"cha":12,"skills":None,"saves":"Dex +6, Con +11, Wis +7","damage_resistances":"fire","senses":"darkvision 120 ft., passive Perception 11","languages":"Aquan, Draconic","environment":["coastal","swamp"],"traits":[{"name":"Amphibious","desc":"The dragon turtle can breathe air and water."}],"actions":[{"name":"Multiattack","desc":"The dragon turtle makes three attacks: one with its bite and two with its claws."},{"name":"Bite","desc":"Melee Weapon Attack: +13 to hit, reach 15 ft., one target. Hit: 26 (3d12 + 7) piercing damage."},{"name":"Claw","desc":"Melee Weapon Attack: +13 to hit, reach 10 ft., one target. Hit: 16 (2d8 + 7) slashing damage."},{"name":"Steam Breath (Recharge 5-6)","desc":"The dragon turtle exhales scalding steam in a 60-foot cone. Each creature in that area must make a DC 18 Constitution saving throw, taking 52 (15d6) fire damage on a failed save, or half as much on a success."}],"legendary_actions":[]},
    {"name": "Stone Golem","type":"construct","size":"large","alignment":"unaligned","cr":10,"xp":5900,"ac":17,"ac_type":"natural armor","hp":"178 (17d10+85)","hp_avg":178,"speed":"30 ft.","str":22,"dex":9,"con":20,"int":3,"wis":11,"cha":1,"skills":None,"saves":None,"damage_immunities":"poison, psychic; bludgeoning, piercing, and slashing from nonmagical attacks not made with adamantine weapons","condition_immunities":"charmed, exhaustion, frightened, paralyzed, petrified, poisoned","senses":"darkvision 120 ft., passive Perception 10","languages":"understands the languages of its creator but can't speak","environment":["underdark","urban"],"traits":[{"name":"Immutable Form","desc":"The golem is immune to any spell or effect that would alter its form."},{"name":"Magic Resistance","desc":"The golem has advantage on saving throws against spells and other magical effects."},{"name":"Magic Weapons","desc":"The golem's weapon attacks are magical."}],"actions":[{"name":"Multiattack","desc":"The golem makes two slam attacks."},{"name":"Slam","desc":"Melee Weapon Attack: +10 to hit, reach 5 ft., one target. Hit: 19 (3d8 + 6) bludgeoning damage."},{"name":"Slow (Recharge 5-6)","desc":"The golem targets one or more creatures it can see within 10 ft. of it. Each target must make a DC 17 Wisdom saving throw against this magic. On a failed save, a target can't use reactions, its speed is halved, and it can't make more than one attack on its turn."}],"legendary_actions":[]},
    {"name": "Clay Golem","type":"construct","size":"large","alignment":"unaligned","cr":9,"xp":5000,"ac":14,"ac_type":"natural armor","hp":"133 (14d10+56)","hp_avg":133,"speed":"20 ft.","str":20,"dex":9,"con":18,"int":3,"wis":8,"cha":1,"skills":None,"saves":None,"damage_immunities":"acid, poison, psychic; bludgeoning, piercing, and slashing from nonmagical attacks not made with adamantine weapons","condition_immunities":"charmed, exhaustion, frightened, paralyzed, petrified, poisoned","senses":"darkvision 60 ft., passive Perception 9","languages":"understands the languages of its creator but can't speak","environment":["underdark","urban"],"traits":[{"name":"Acid Absorption","desc":"Whenever the golem is subjected to acid damage, it takes no damage and instead regains a number of hit points equal to the acid damage dealt."},{"name":"Berserk","desc":"Whenever the golem starts its turn with 60 hit points or fewer, roll a d6. On a 6, the golem goes berserk."},{"name":"Immutable Form","desc":"The golem is immune to any spell or effect that would alter its form."},{"name":"Magic Resistance","desc":"The golem has advantage on saving throws against spells and other magical effects."}],"actions":[{"name":"Multiattack","desc":"The golem makes two slam attacks."},{"name":"Slam","desc":"Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 16 (2d10 + 5) bludgeoning damage. If the target is a creature, it must succeed on a DC 15 Constitution saving throw or have its hit point maximum reduced by an amount equal to the damage taken."},{"name":"Haste (Recharge 5-6)","desc":"Until the end of its next turn, the golem magically gains a +2 bonus to its AC, has advantage on Dexterity saving throws, and can use its slam attack as a bonus action."}],"legendary_actions":[]},
    {"name": "Iron Golem","type":"construct","size":"large","alignment":"unaligned","cr":16,"xp":15000,"ac":20,"ac_type":"natural armor","hp":"210 (20d10+100)","hp_avg":210,"speed":"30 ft.","str":24,"dex":9,"con":20,"int":3,"wis":11,"cha":1,"skills":None,"saves":None,"damage_immunities":"fire, poison, psychic; bludgeoning, piercing, and slashing from nonmagical attacks not made with adamantine weapons","condition_immunities":"charmed, exhaustion, frightened, paralyzed, petrified, poisoned","senses":"darkvision 120 ft., passive Perception 10","languages":"understands the languages of its creator but can't speak","environment":["underdark","urban"],"traits":[{"name":"Fire Absorption","desc":"Whenever the golem is subjected to fire damage, it takes no damage and instead regains a number of hit points equal to the fire damage dealt."},{"name":"Immutable Form","desc":"The golem is immune to any spell or effect that would alter its form."},{"name":"Magic Resistance","desc":"The golem has advantage on saving throws against spells and other magical effects."},{"name":"Magic Weapons","desc":"The golem's weapon attacks are magical."}],"actions":[{"name":"Multiattack","desc":"The golem makes two melee attacks."},{"name":"Slam","desc":"Melee Weapon Attack: +13 to hit, reach 5 ft., one target. Hit: 20 (3d8 + 7) bludgeoning damage."},{"name":"Sword","desc":"Melee Weapon Attack: +13 to hit, reach 10 ft., one target. Hit: 23 (3d10 + 7) slashing damage."},{"name":"Poison Breath (Recharge 5-6)","desc":"The golem exhales poisonous gas in a 15-foot cone. Each creature in that area must make a DC 19 Constitution saving throw, taking 45 (10d8) poison damage on a failed save, or half as much on a successful one."}],"legendary_actions":[]},
    {"name": "Chimera","type":"monstrosity","size":"large","alignment":"chaotic evil","cr":6,"xp":2300,"ac":14,"ac_type":"natural armor","hp":"114 (12d10+48)","hp_avg":114,"speed":"30 ft., fly 60 ft.","str":19,"dex":11,"con":19,"int":3,"wis":14,"cha":10,"skills":"Perception +8","saves":None,"senses":"darkvision 60 ft., passive Perception 18","languages":"understands Draconic but can't speak","environment":["mountain","grassland"],"traits":[],"actions":[{"name":"Multiattack","desc":"The chimera makes three attacks: one with its bite, one with its horns, and one with its claws."},{"name":"Bite","desc":"Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) piercing damage."},{"name":"Horns","desc":"Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 10 (1d12 + 4) bludgeoning damage."},{"name":"Claws","desc":"Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 11 (2d6 + 4) slashing damage."},{"name":"Fire Breath (Recharge 5-6)","desc":"The dragon head exhales fire in a 15-foot cone. Each creature in that area must make a DC 15 Dexterity saving throw, taking 31 (7d8) fire damage on a failed save, or half as much on a success."}],"legendary_actions":[]},
    {"name": "Manticore","type":"monstrosity","size":"large","alignment":"lawful evil","cr":3,"xp":700,"ac":14,"ac_type":"natural armor","hp":"68 (8d10+24)","hp_avg":68,"speed":"30 ft., fly 50 ft.","str":17,"dex":16,"con":17,"int":7,"wis":12,"cha":8,"skills":None,"saves":None,"senses":"darkvision 60 ft., passive Perception 11","languages":"Common","environment":["mountain","grassland","coastal"],"traits":[{"name":"Tail Spike Regrowth","desc":"The manticore has twenty-four tail spikes. Used spikes regrow when the manticore finishes a long rest."}],"actions":[{"name":"Multiattack","desc":"The manticore makes three attacks: one with its bite and two with its claws or three with its tail spikes."},{"name":"Bite","desc":"Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) piercing damage."},{"name":"Claw","desc":"Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 6 (1d6 + 3) slashing damage."},{"name":"Tail Spike","desc":"Ranged Weapon Attack: +5 to hit, range 100/200 ft., one target. Hit: 7 (1d8 + 3) piercing damage."}],"legendary_actions":[]},
    {"name": "Basilisk","type":"monstrosity","size":"medium","alignment":"unaligned","cr":3,"xp":700,"ac":15,"ac_type":"natural armor","hp":"52 (8d8+16)","hp_avg":52,"speed":"20 ft.","str":16,"dex":8,"con":15,"int":2,"wis":8,"cha":7,"skills":None,"saves":None,"senses":"darkvision 60 ft., passive Perception 9","languages":"—","environment":["mountain","underdark"],"traits":[{"name":"Petrifying Gaze","desc":"If a creature starts its turn within 30 ft. of the basilisk and the two of them can see each other, the basilisk can force the creature to make a DC 12 Constitution saving throw. On a failure, the creature magically begins to turn to stone and is restrained."}],"actions":[{"name":"Bite","desc":"Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) piercing damage plus 7 (2d6) poison damage."}],"legendary_actions":[]},
    {"name": "Medusa","type":"monstrosity","size":"medium","alignment":"lawful evil","cr":6,"xp":2300,"ac":15,"ac_type":"natural armor","hp":"127 (17d8+51)","hp_avg":127,"speed":"30 ft.","str":10,"dex":15,"con":16,"int":12,"wis":13,"cha":15,"skills":"Deception +5, Insight +4, Perception +4, Stealth +5","saves":None,"senses":"darkvision 60 ft., passive Perception 14","languages":"Common","environment":["desert","underdark"],"traits":[{"name":"Petrifying Gaze","desc":"When a creature that can see the medusa's eyes starts its turn within 30 ft. of the medusa, the medusa can force it to make a DC 14 Constitution saving throw. On a failure, the creature is restrained and begins to turn to stone."}],"actions":[{"name":"Multiattack","desc":"The medusa makes either three melee attacks — one with its snake hair and two with its shortsword — or two ranged attacks with its longbow."},{"name":"Snake Hair","desc":"Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 4 (1d4 + 2) piercing damage plus 14 (4d6) poison damage."},{"name":"Shortsword","desc":"Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 5 (1d6 + 2) piercing damage."},{"name":"Longbow","desc":"Ranged Weapon Attack: +5 to hit, range 150/600 ft., one target. Hit: 6 (1d8 + 2) piercing damage plus 7 (2d6) poison damage."}],"legendary_actions":[]},
    {"name": "Treant","type":"plant","size":"huge","alignment":"chaotic good","cr":9,"xp":5000,"ac":16,"ac_type":"natural armor","hp":"138 (12d12+60)","hp_avg":138,"speed":"30 ft.","str":23,"dex":8,"con":21,"int":12,"wis":16,"cha":12,"skills":None,"saves":None,"damage_vulnerabilities":"fire","damage_resistances":"bludgeoning, piercing","senses":"passive Perception 13","languages":"Common, Druidic, Elvish, Sylvan","environment":["forest"],"traits":[{"name":"False Appearance","desc":"While the treant remains motionless, it is indistinguishable from a normal tree."},{"name":"Siege Monster","desc":"The treant deals double damage to objects and structures."}],"actions":[{"name":"Multiattack","desc":"The treant makes two slam attacks."},{"name":"Slam","desc":"Melee Weapon Attack: +10 to hit, reach 5 ft., one target. Hit: 16 (3d6 + 6) bludgeoning damage."},{"name":"Rock","desc":"Ranged Weapon Attack: +10 to hit, range 60/180 ft., one target. Hit: 28 (4d10 + 6) bludgeoning damage."},{"name":"Animate Trees (1/Day)","desc":"The treant magically animates one or two trees it can see within 60 ft. of it. These trees have the same statistics as a treant except they have Intelligence and Charisma scores of 1."}],"legendary_actions":[]},
    {"name": "Shambling Mound","type":"plant","size":"large","alignment":"unaligned","cr":5,"xp":1800,"ac":15,"ac_type":"natural armor","hp":"136 (16d10+48)","hp_avg":136,"speed":"20 ft., swim 20 ft.","str":18,"dex":8,"con":16,"int":5,"wis":10,"cha":5,"skills":"Stealth +2","saves":None,"damage_resistances":"cold, fire","damage_immunities":"lightning","condition_immunities":"blinded, deafened, exhaustion","senses":"blindsight 60 ft. (blind beyond this radius), passive Perception 10","languages":"—","environment":["forest","swamp"],"traits":[{"name":"Lightning Absorption","desc":"Whenever the shambling mound is subjected to lightning damage, it takes no damage and regains a number of hit points equal to the lightning damage dealt."}],"actions":[{"name":"Multiattack","desc":"The shambling mound makes two slam attacks."},{"name":"Slam","desc":"Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 13 (2d8 + 4) bludgeoning damage."},{"name":"Engulf","desc":"The shambling mound engulfs a Medium or smaller creature grappled by it. The engulfed target is blinded, restrained, and unable to breathe."}],"legendary_actions":[]},
    {"name": "Roc","type":"monstrosity","size":"gargantuan","alignment":"unaligned","cr":11,"xp":7200,"ac":15,"ac_type":"natural armor","hp":"248 (16d20+80)","hp_avg":248,"speed":"20 ft., fly 120 ft.","str":28,"dex":10,"con":20,"int":3,"wis":10,"cha":9,"skills":"Perception +4","saves":"Dex +4, Con +9, Wis +4, Cha +3","senses":"passive Perception 14","languages":"—","environment":["coastal","mountain"],"traits":[{"name":"Keen Sight","desc":"The roc has advantage on Wisdom (Perception) checks that rely on sight."}],"actions":[{"name":"Multiattack","desc":"The roc makes two attacks: one with its beak and one with its talons."},{"name":"Beak","desc":"Melee Weapon Attack: +13 to hit, reach 10 ft., one target. Hit: 27 (4d8 + 9) piercing damage."},{"name":"Talons","desc":"Melee Weapon Attack: +13 to hit, reach 5 ft., one target. Hit: 23 (4d6 + 9) slashing damage, and the target is grappled (escape DC 19)."}],"legendary_actions":[]},
    {"name": "Hydra","type":"monstrosity","size":"huge","alignment":"unaligned","cr":8,"xp":3900,"ac":15,"ac_type":"natural armor","hp":"172 (15d12+75)","hp_avg":172,"speed":"30 ft., swim 30 ft.","str":20,"dex":12,"con":20,"int":2,"wis":10,"cha":7,"skills":"Perception +6","saves":None,"senses":"darkvision 60 ft., passive Perception 16","languages":"—","environment":["swamp","coastal","underdark"],"traits":[{"name":"Hold Breath","desc":"The hydra can hold its breath for 1 hour."},{"name":"Multiple Heads","desc":"The hydra has five heads. While it has more than one head, the hydra has advantage on saving throws against being blinded, charmed, deafened, frightened, stunned, and knocked unconscious."},{"name":"Reactive Heads","desc":"For each head the hydra has beyond one, it gets an extra reaction that can be used only for opportunity attacks."},{"name":"Wakeful","desc":"While the hydra sleeps, at least one of its heads is awake."}],"actions":[{"name":"Multiattack","desc":"The hydra makes as many bite attacks as it has heads."},{"name":"Bite","desc":"Melee Weapon Attack: +8 to hit, reach 10 ft., one target. Hit: 10 (1d10 + 5) piercing damage."}],"legendary_actions":[]},
    {"name": "Purple Worm","type":"monstrosity","size":"gargantuan","alignment":"unaligned","cr":15,"xp":13000,"ac":18,"ac_type":"natural armor","hp":"247 (15d20+90)","hp_avg":247,"speed":"50 ft., burrow 30 ft.","str":28,"dex":7,"con":22,"int":1,"wis":8,"cha":4,"skills":None,"saves":"Con +11, Wis +4","senses":"blindsight 30 ft., tremorsense 60 ft., passive Perception 9","languages":"—","environment":["underdark","desert","mountain"],"traits":[{"name":"Tunneler","desc":"The worm can burrow through solid rock at half its burrow speed and leaves a 10-foot-diameter tunnel in its wake."}],"actions":[{"name":"Multiattack","desc":"The worm makes two attacks: one with its bite and one with its tail stinger."},{"name":"Bite","desc":"Melee Weapon Attack: +14 to hit, reach 10 ft., one target. Hit: 22 (3d8 + 9) piercing damage. If the target is a Large or smaller creature, it must succeed on a DC 19 Dexterity saving throw or be swallowed by the worm."},{"name":"Tail Stinger","desc":"Melee Weapon Attack: +14 to hit, reach 10 ft., one creature. Hit: 19 (3d6 + 9) piercing damage plus 21 (6d6) poison damage."}],"legendary_actions":[]},
    {"name": "Bulette","type":"monstrosity","size":"large","alignment":"unaligned","cr":5,"xp":1800,"ac":17,"ac_type":"natural armor","hp":"94 (9d10+45)","hp_avg":94,"speed":"40 ft., burrow 40 ft.","str":19,"dex":11,"con":21,"int":2,"wis":10,"cha":5,"skills":"Perception +6","saves":None,"senses":"darkvision 60 ft., tremorsense 60 ft., passive Perception 16","languages":"—","environment":["grassland","mountain"],"traits":[{"name":"Standing Leap","desc":"The bulette's long jump is up to 30 ft. and its high jump is up to 15 ft., with or without a running start."}],"actions":[{"name":"Bite","desc":"Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 30 (4d12 + 4) piercing damage."},{"name":"Deadly Leap","desc":"If the bulette jumps at least 15 ft. as part of its movement, it can use this action to land on its feet in a space that contains one or more other creatures. Each of those creatures must succeed on a DC 16 Strength or Dexterity saving throw or be knocked prone and take 14 (3d6 + 4) bludgeoning damage plus 14 (3d6 + 4) slashing damage."}],"legendary_actions":[]},
    {"name": "Remorhaz","type":"monstrosity","size":"huge","alignment":"unaligned","cr":11,"xp":7200,"ac":17,"ac_type":"natural armor","hp":"195 (17d12+85)","hp_avg":195,"speed":"30 ft., burrow 20 ft.","str":24,"dex":13,"con":21,"int":4,"wis":10,"cha":5,"skills":None,"saves":None,"damage_immunities":"cold, fire","senses":"darkvision 60 ft., tremorsense 60 ft., passive Perception 10","languages":"—","environment":["arctic"],"traits":[{"name":"Heated Body","desc":"A creature that touches the remorhaz or hits it with a melee attack while within 5 ft. of it takes 10 (3d6) fire damage."}],"actions":[{"name":"Bite","desc":"Melee Weapon Attack: +11 to hit, reach 10 ft., one target. Hit: 40 (6d10 + 7) piercing damage plus 10 (3d6) fire damage. If the target is a creature, it is grappled (escape DC 17)."},{"name":"Swallow","desc":"The remorhaz makes one bite attack against a Medium or smaller creature it is grappling. If the attack hits, that creature takes the bite's damage and is swallowed."}],"legendary_actions":[]},
    {"name": "Roper","type":"monstrosity","size":"large","alignment":"neutral evil","cr":5,"xp":1800,"ac":20,"ac_type":"natural armor","hp":"93 (11d10+33)","hp_avg":93,"speed":"10 ft., climb 10 ft.","str":18,"dex":8,"con":17,"int":7,"wis":16,"cha":6,"skills":"Perception +6, Stealth +5","saves":None,"damage_vulnerabilities":"None","senses":"darkvision 60 ft., passive Perception 16","languages":"—","environment":["underdark"],"traits":[{"name":"False Appearance","desc":"While the roper remains motionless, it is indistinguishable from a normal cave formation, such as a stalagmite."},{"name":"Grasping Tendrils","desc":"The roper can have up to six tendrils at a time. Each tendril can be attacked (AC 20; 10 hit points; immunity to poison and psychic damage)."},{"name":"Spider Climb","desc":"The roper can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check."}],"actions":[{"name":"Multiattack","desc":"The roper makes four attacks with its tendrils, then pulls each creature grappled by a tendril up to 25 ft. straight toward it."},{"name":"Tendril","desc":"Melee Weapon Attack: +7 to hit, reach 50 ft., one creature. Hit: Target is grappled (escape DC 15). Until grapple ends, target is restrained and has disadvantage on Strength checks and Strength saving throws."},{"name":"Reel","desc":"The roper pulls each creature grappled by it up to 25 ft. straight toward it."},{"name":"Bite","desc":"Melee Weapon Attack: +7 to hit, reach 5 ft., one target. Hit: 22 (4d8 + 4) piercing damage."}],"legendary_actions":[]},
    {"name": "Rust Monster","type":"monstrosity","size":"medium","alignment":"unaligned","cr":0.5,"xp":100,"ac":14,"ac_type":"natural armor","hp":"27 (5d8+5)","hp_avg":27,"speed":"40 ft.","str":13,"dex":12,"con":13,"int":2,"wis":13,"cha":6,"skills":None,"saves":None,"senses":"darkvision 60 ft., passive Perception 11","languages":"—","environment":["underdark"],"traits":[{"name":"Iron Scent","desc":"The rust monster can pinpoint, by scent, the location of ferrous metal within 30 ft. of it."},{"name":"Rust Metal","desc":"Any nonmagical weapon made of metal that hits the rust monster corrodes. After dealing damage, the weapon takes a permanent and cumulative -1 penalty to damage rolls."}],"actions":[{"name":"Bite","desc":"Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 5 (1d8 + 1) piercing damage."},{"name":"Antennae","desc":"The rust monster corrodes a nonmagical ferrous metal object it can see within 5 ft. of it."}],"legendary_actions":[]},
    {"name": "Drider","type":"monstrosity","size":"large","alignment":"chaotic evil","cr":6,"xp":2300,"ac":19,"ac_type":"natural armor","hp":"123 (13d10+52)","hp_avg":123,"speed":"30 ft., climb 30 ft.","str":16,"dex":16,"con":18,"int":13,"wis":14,"cha":12,"skills":"Perception +5, Stealth +9","saves":None,"senses":"darkvision 120 ft., passive Perception 15","languages":"Elvish, Undercommon","environment":["underdark"],"traits":[{"name":"Fey Ancestry","desc":"The drider has advantage on saving throws against being charmed, and magic can't put the drider to sleep."},{"name":"Innate Spellcasting","desc":"The drider's innate spellcasting ability is Wisdom (spell save DC 13). At will: dancing lights. 1/day each: darkness, faerie fire."},{"name":"Spider Climb","desc":"The drider can climb difficult surfaces, including upside down on ceilings, without needing to make an ability check."},{"name":"Sunlight Sensitivity","desc":"While in sunlight, the drider has disadvantage on attack rolls, as well as on Wisdom (Perception) checks that rely on sight."},{"name":"Web Walker","desc":"The drider ignores movement restrictions caused by webbing."}],"actions":[{"name":"Multiattack","desc":"The drider makes three attacks, either with its longsword or its longbow. It can replace one with a bite attack."},{"name":"Bite","desc":"Melee Weapon Attack: +6 to hit, reach 5 ft., one creature. Hit: 2 (1d4) piercing damage plus 9 (2d8) poison damage."},{"name":"Longsword","desc":"Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 7 (1d8 + 3) slashing damage, or 8 (1d10 + 3) slashing damage if used with two hands."},{"name":"Longbow","desc":"Ranged Weapon Attack: +6 to hit, range 150/600 ft., one target. Hit: 7 (1d8 + 3) piercing damage plus 4 (1d8) poison damage."}],"legendary_actions":[]},
    {"name": "Displacer Beast","type":"monstrosity","size":"large","alignment":"lawful evil","cr":3,"xp":700,"ac":13,"ac_type":"natural armor","hp":"85 (10d10+30)","hp_avg":85,"speed":"40 ft.","str":18,"dex":15,"con":16,"int":6,"wis":12,"cha":8,"skills":None,"saves":None,"senses":"darkvision 60 ft., passive Perception 11","languages":"—","environment":["forest","grassland"],"traits":[{"name":"Avoidance","desc":"If the displacer beast is subjected to an effect that allows it to make a saving throw to take only half damage, it instead takes no damage if it succeeds on the saving throw, and only half damage if it fails."},{"name":"Displacement","desc":"The displacer beast projects a magical illusion that makes it appear to be standing near its actual location, causing attack rolls against it to have disadvantage. If it is hit by an attack, this trait is disrupted until the end of its next turn."}],"actions":[{"name":"Multiattack","desc":"The displacer beast makes two attacks with its tentacles."},{"name":"Tentacle","desc":"Melee Weapon Attack: +6 to hit, reach 10 ft., one target. Hit: 7 (1d6 + 4) bludgeoning damage plus 3 (1d6) piercing damage."}],"legendary_actions":[]},
    {"name": "Umber Hulk","type":"monstrosity","size":"large","alignment":"chaotic evil","cr":5,"xp":1800,"ac":18,"ac_type":"natural armor","hp":"93 (11d10+33)","hp_avg":93,"speed":"30 ft., burrow 20 ft.","str":20,"dex":13,"con":16,"int":9,"wis":10,"cha":10,"skills":None,"saves":None,"senses":"darkvision 120 ft., tremorsense 60 ft., passive Perception 10","languages":"Umber Hulk","environment":["underdark"],"traits":[{"name":"Confusing Gaze","desc":"When a creature starts its turn within 30 ft. of the umber hulk and is able to see the umber hulk's eyes, the umber hulk can magically force it to make a DC 15 Charisma saving throw. On a failure, the creature can't take reactions until the start of its next turn and rolls a d8 to determine what it does during that turn."},{"name":"Tunneler","desc":"The umber hulk can burrow through solid rock at half its burrowing speed and leaves a 5-foot-wide, 8-foot-high tunnel in its wake."}],"actions":[{"name":"Multiattack","desc":"The umber hulk makes three attacks: two with its claws and one with its mandibles."},{"name":"Claw","desc":"Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 9 (1d8 + 5) slashing damage."},{"name":"Mandibles","desc":"Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 14 (2d8 + 5) slashing damage."}],"legendary_actions":[]},
]

# ── Seed function ──────────────────────────────────────────────────────────

async def seed():
    await connect_db()
    pool = get_pool()

    # Check if already seeded
    count = await pool.fetchval("SELECT count(*) FROM bestiary")
    if count > 0:
        print(f"Bestiary already has {count} creatures. Skipping seed.")
        await close_db()
        return

    inserted = 0
    for c in CREATURES:
        try:
            await pool.execute(
                """
                INSERT INTO bestiary (name, type, size, alignment, cr, xp, ac, ac_type,
                    hp, hp_avg, speed, str, dex, con, int, wis, cha,
                    skills, saves, damage_resistances, damage_immunities, condition_immunities,
                    senses, languages, traits, actions, legendary_actions, environment)
                VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,
                        $18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28)
                """,
                c["name"], c["type"], c["size"], c["alignment"],
                c["cr"], c["xp"], c["ac"], c.get("ac_type"),
                c["hp"], c["hp_avg"], c["speed"],
                c["str"], c["dex"], c["con"], c["int"], c["wis"], c["cha"],
                c.get("skills"), c.get("saves"),
                c.get("damage_resistances"), c.get("damage_immunities"), c.get("condition_immunities"),
                c["senses"], c["languages"],
                json.dumps(c.get("traits", [])),
                json.dumps(c.get("actions", [])),
                json.dumps(c.get("legendary_actions", [])),
                c.get("environment", []),
            )
            inserted += 1
        except Exception as e:
            print(f"  Error inserting {c['name']}: {e}")

    print(f"✅ Seeded {inserted} creatures into bestiary.")
    await close_db()


if __name__ == "__main__":
    asyncio.run(seed())
