"""
Seed the items table with SRD 5.1 equipment and magic items.
Run: uv run python scripts/seed_items.py
"""
import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "backend"))

from app.db import connect_db, close_db, get_pool

ITEMS = [
    # ── Weapons ──────────────────────────────────────────────────────────
    {"name": "Club", "category": "weapon", "rarity": "common", "cost": "1 sp", "weight": "2 lb.",
     "description": "Simple melee weapon.", "properties": ["light"], "damage": "1d4 bludgeoning"},
    {"name": "Dagger", "category": "weapon", "rarity": "common", "cost": "2 gp", "weight": "1 lb.",
     "description": "Simple melee weapon with the finesse, light, and thrown (range 20/60) properties.",
     "properties": ["finesse", "light", "thrown"], "damage": "1d4 piercing"},
    {"name": "Quarterstaff", "category": "weapon", "rarity": "common", "cost": "2 sp", "weight": "4 lb.",
     "description": "Simple melee weapon.", "properties": ["versatile"], "damage": "1d6 bludgeoning"},
    {"name": "Light Crossbow", "category": "weapon", "rarity": "common", "cost": "25 gp", "weight": "5 lb.",
     "description": "Simple ranged weapon (range 80/320). Loading, two-handed.",
     "properties": ["ammunition", "loading", "two-handed"], "damage": "1d8 piercing"},
    {"name": "Shortbow", "category": "weapon", "rarity": "common", "cost": "25 gp", "weight": "2 lb.",
     "description": "Simple ranged weapon (range 80/320). Two-handed.",
     "properties": ["ammunition", "two-handed"], "damage": "1d6 piercing"},
    {"name": "Longsword", "category": "weapon", "rarity": "common", "cost": "15 gp", "weight": "3 lb.",
     "description": "Martial melee weapon.", "properties": ["versatile"], "damage": "1d8 slashing"},
    {"name": "Greatsword", "category": "weapon", "rarity": "common", "cost": "50 gp", "weight": "6 lb.",
     "description": "Martial melee weapon. Heavy, two-handed.",
     "properties": ["heavy", "two-handed"], "damage": "2d6 slashing"},
    {"name": "Rapier", "category": "weapon", "rarity": "common", "cost": "25 gp", "weight": "2 lb.",
     "description": "Martial melee weapon.", "properties": ["finesse"], "damage": "1d8 piercing"},
    {"name": "Longbow", "category": "weapon", "rarity": "common", "cost": "50 gp", "weight": "2 lb.",
     "description": "Martial ranged weapon (range 150/600). Heavy, two-handed.",
     "properties": ["ammunition", "heavy", "two-handed"], "damage": "1d8 piercing"},
    {"name": "Battleaxe", "category": "weapon", "rarity": "common", "cost": "10 gp", "weight": "4 lb.",
     "description": "Martial melee weapon.", "properties": ["versatile"], "damage": "1d8 slashing"},
    {"name": "Warhammer", "category": "weapon", "rarity": "common", "cost": "15 gp", "weight": "2 lb.",
     "description": "Martial melee weapon.", "properties": ["versatile"], "damage": "1d8 bludgeoning"},
    {"name": "Scimitar", "category": "weapon", "rarity": "common", "cost": "25 gp", "weight": "3 lb.",
     "description": "Martial melee weapon.", "properties": ["finesse", "light"], "damage": "1d6 slashing"},
    {"name": "Handaxe", "category": "weapon", "rarity": "common", "cost": "5 gp", "weight": "2 lb.",
     "description": "Simple melee weapon with the light and thrown (range 20/60) properties.",
     "properties": ["light", "thrown"], "damage": "1d6 slashing"},
    {"name": "Javelin", "category": "weapon", "rarity": "common", "cost": "5 sp", "weight": "2 lb.",
     "description": "Simple melee weapon with the thrown property (range 30/120).",
     "properties": ["thrown"], "damage": "1d6 piercing"},

    # ── Armor ────────────────────────────────────────────────────────────
    {"name": "Padded Armor", "category": "armor", "rarity": "common", "cost": "5 gp", "weight": "8 lb.",
     "description": "Light armor. Disadvantage on Stealth checks.", "armor_type": "light", "ac": 11},
    {"name": "Leather Armor", "category": "armor", "rarity": "common", "cost": "10 gp", "weight": "10 lb.",
     "description": "Light armor.", "armor_type": "light", "ac": 11},
    {"name": "Studded Leather Armor", "category": "armor", "rarity": "common", "cost": "45 gp", "weight": "13 lb.",
     "description": "Light armor.", "armor_type": "light", "ac": 12},
    {"name": "Hide Armor", "category": "armor", "rarity": "common", "cost": "10 gp", "weight": "12 lb.",
     "description": "Medium armor.", "armor_type": "medium", "ac": 12},
    {"name": "Chain Shirt", "category": "armor", "rarity": "common", "cost": "50 gp", "weight": "20 lb.",
     "description": "Medium armor.", "armor_type": "medium", "ac": 13},
    {"name": "Scale Mail", "category": "armor", "rarity": "common", "cost": "50 gp", "weight": "45 lb.",
     "description": "Medium armor. Disadvantage on Stealth checks.", "armor_type": "medium", "ac": 14},
    {"name": "Breastplate", "category": "armor", "rarity": "common", "cost": "400 gp", "weight": "20 lb.",
     "description": "Medium armor.", "armor_type": "medium", "ac": 14},
    {"name": "Half Plate Armor", "category": "armor", "rarity": "common", "cost": "750 gp", "weight": "40 lb.",
     "description": "Medium armor. Disadvantage on Stealth checks.", "armor_type": "medium", "ac": 15},
    {"name": "Ring Mail", "category": "armor", "rarity": "common", "cost": "30 gp", "weight": "40 lb.",
     "description": "Heavy armor. Disadvantage on Stealth checks.", "armor_type": "heavy", "ac": 14},
    {"name": "Chain Mail", "category": "armor", "rarity": "common", "cost": "75 gp", "weight": "55 lb.",
     "description": "Heavy armor. Disadvantage on Stealth checks. Requires Str 13.", "armor_type": "heavy", "ac": 16},
    {"name": "Splint Armor", "category": "armor", "rarity": "common", "cost": "200 gp", "weight": "60 lb.",
     "description": "Heavy armor. Disadvantage on Stealth checks. Requires Str 15.", "armor_type": "heavy", "ac": 17},
    {"name": "Plate Armor", "category": "armor", "rarity": "common", "cost": "1500 gp", "weight": "65 lb.",
     "description": "Heavy armor. Disadvantage on Stealth checks. Requires Str 15.", "armor_type": "heavy", "ac": 18},
    {"name": "Shield", "category": "armor", "rarity": "common", "cost": "10 gp", "weight": "6 lb.",
     "description": "A shield is made from wood or metal and is carried in one hand. +2 AC.", "armor_type": "shield", "ac": 2},

    # ── Potions ──────────────────────────────────────────────────────────
    {"name": "Potion of Healing", "category": "potion", "rarity": "common", "cost": "50 gp", "weight": "½ lb.",
     "description": "You regain 2d4+2 hit points when you drink this potion."},
    {"name": "Potion of Greater Healing", "category": "potion", "rarity": "uncommon", "cost": "150 gp", "weight": "½ lb.",
     "description": "You regain 4d4+4 hit points when you drink this potion."},
    {"name": "Potion of Superior Healing", "category": "potion", "rarity": "rare", "cost": "450 gp", "weight": "½ lb.",
     "description": "You regain 8d4+8 hit points when you drink this potion."},
    {"name": "Potion of Supreme Healing", "category": "potion", "rarity": "very_rare", "cost": "1350 gp", "weight": "½ lb.",
     "description": "You regain 10d4+20 hit points when you drink this potion."},
    {"name": "Potion of Invisibility", "category": "potion", "rarity": "very_rare", "cost": "180 gp", "weight": "½ lb.",
     "description": "When you drink this potion, you become invisible for 1 hour. Anything you wear or carry is invisible with you."},
    {"name": "Potion of Speed", "category": "potion", "rarity": "very_rare", "cost": "400 gp", "weight": "½ lb.",
     "description": "When you drink this potion, you gain the effect of the Haste spell for 1 minute (no concentration required)."},
    {"name": "Potion of Flying", "category": "potion", "rarity": "very_rare", "cost": "500 gp", "weight": "½ lb.",
     "description": "When you drink this potion, you gain a flying speed equal to your walking speed for 1 hour."},
    {"name": "Potion of Water Breathing", "category": "potion", "rarity": "uncommon", "cost": "180 gp", "weight": "½ lb.",
     "description": "You can breathe underwater for 1 hour after drinking this potion."},
    {"name": "Potion of Fire Resistance", "category": "potion", "rarity": "uncommon", "cost": "200 gp", "weight": "½ lb.",
     "description": "When you drink this potion, you gain resistance to fire damage for 1 hour."},
    {"name": "Potion of Giant Strength (Hill)", "category": "potion", "rarity": "uncommon", "cost": "200 gp", "weight": "½ lb.",
     "description": "When you drink this potion, your Strength score changes to 21 for 1 hour."},
    {"name": "Potion of Giant Strength (Frost/Stone)", "category": "potion", "rarity": "rare", "cost": "500 gp", "weight": "½ lb.",
     "description": "When you drink this potion, your Strength score changes to 23 for 1 hour."},
    {"name": "Potion of Giant Strength (Fire)", "category": "potion", "rarity": "rare", "cost": "800 gp", "weight": "½ lb.",
     "description": "When you drink this potion, your Strength score changes to 25 for 1 hour."},
    {"name": "Potion of Giant Strength (Cloud)", "category": "potion", "rarity": "very_rare", "cost": "1500 gp", "weight": "½ lb.",
     "description": "When you drink this potion, your Strength score changes to 27 for 1 hour."},
    {"name": "Antitoxin", "category": "potion", "rarity": "common", "cost": "50 gp", "weight": "—",
     "description": "A creature that drinks this vial of liquid gains advantage on saving throws against poison for 1 hour."},

    # ── Scrolls ──────────────────────────────────────────────────────────
    {"name": "Spell Scroll (Cantrip)", "category": "scroll", "rarity": "common", "cost": "30 gp", "weight": "—",
     "description": "A spell scroll bears the words of a single cantrip, written in a mystical cipher."},
    {"name": "Spell Scroll (1st Level)", "category": "scroll", "rarity": "common", "cost": "60 gp", "weight": "—",
     "description": "A spell scroll bears the words of a single 1st-level spell, written in a mystical cipher."},
    {"name": "Spell Scroll (2nd Level)", "category": "scroll", "rarity": "uncommon", "cost": "120 gp", "weight": "—",
     "description": "A spell scroll bears the words of a single 2nd-level spell, written in a mystical cipher."},
    {"name": "Spell Scroll (3rd Level)", "category": "scroll", "rarity": "uncommon", "cost": "200 gp", "weight": "—",
     "description": "A spell scroll bears the words of a single 3rd-level spell, written in a mystical cipher."},
    {"name": "Scroll of Protection", "category": "scroll", "rarity": "rare", "cost": "180 gp", "weight": "—",
     "description": "Each scroll of protection works against a specific creature type. Using an action to read the scroll encloses you in an invisible barrier for 5 minutes."},

    # ── Rings ────────────────────────────────────────────────────────────
    {"name": "Ring of Protection", "category": "ring", "rarity": "rare", "cost": "5000 gp", "attunement": True, "weight": "—",
     "description": "You gain a +1 bonus to AC and saving throws while wearing this ring."},
    {"name": "Ring of Jumping", "category": "ring", "rarity": "uncommon", "cost": "2500 gp", "attunement": True, "weight": "—",
     "description": "While wearing this ring, you can cast the Jump spell from it as a bonus action at will."},
    {"name": "Ring of Swimming", "category": "ring", "rarity": "uncommon", "cost": "3000 gp", "weight": "—",
     "description": "You have a swimming speed of 40 feet while wearing this ring."},
    {"name": "Ring of Warmth", "category": "ring", "rarity": "uncommon", "cost": "1000 gp", "attunement": True, "weight": "—",
     "description": "While wearing this ring, you have resistance to cold damage."},
    {"name": "Ring of Water Walking", "category": "ring", "rarity": "uncommon", "cost": "1500 gp", "weight": "—",
     "description": "While wearing this ring, you can stand on and move across any liquid surface as if it were solid ground."},
    {"name": "Ring of Mind Shielding", "category": "ring", "rarity": "uncommon", "cost": "1600 gp", "attunement": True, "weight": "—",
     "description": "While wearing this ring, you are immune to magic that allows other creatures to read your thoughts."},
    {"name": "Ring of Evasion", "category": "ring", "rarity": "rare", "cost": "5000 gp", "attunement": True, "weight": "—",
     "description": "This ring has 3 charges. When you fail a Dexterity saving throw, you can use your reaction to expend 1 charge to succeed instead."},
    {"name": "Ring of Resistance", "category": "ring", "rarity": "rare", "cost": "6000 gp", "attunement": True, "weight": "—",
     "description": "You have resistance to one damage type while wearing this ring (chosen by the DM)."},
    {"name": "Ring of Invisibility", "category": "ring", "rarity": "legendary", "cost": "10000 gp", "attunement": True, "weight": "—",
     "description": "While wearing this ring, you can turn invisible as an action. You remain invisible until the ring is removed."},
    {"name": "Ring of Regeneration", "category": "ring", "rarity": "very_rare", "cost": "20000 gp", "attunement": True, "weight": "—",
     "description": "While wearing this ring, you regain 1d6 hit points every 10 minutes, provided you have at least 1 hit point."},

    # ── Wands ────────────────────────────────────────────────────────────
    {"name": "Wand of Magic Detection", "category": "wand", "rarity": "uncommon", "cost": "1500 gp", "weight": "1 lb.",
     "description": "This wand has 3 charges. While holding it, you can expend 1 charge to cast Detect Magic from it."},
    {"name": "Wand of Secrets", "category": "wand", "rarity": "uncommon", "cost": "1500 gp", "weight": "1 lb.",
     "description": "This wand has 3 charges. While holding it, you can expend 1 charge to detect secret doors or traps within 30 feet."},
    {"name": "Wand of Magic Missiles", "category": "wand", "rarity": "uncommon", "cost": "8000 gp", "weight": "1 lb.",
     "description": "This wand has 7 charges. While holding it, you can use an action to expend 1 or more charges to cast Magic Missile."},
    {"name": "Wand of Web", "category": "wand", "rarity": "uncommon", "cost": "3000 gp", "attunement": True, "weight": "1 lb.",
     "description": "This wand has 7 charges. While holding it, you can use an action to expend 1 charge to cast Web (save DC 15)."},
    {"name": "Wand of Fireballs", "category": "wand", "rarity": "rare", "cost": "32000 gp", "attunement": True, "weight": "1 lb.",
     "description": "This wand has 7 charges. While holding it, you can use an action to expend 1 or more charges to cast Fireball (save DC 15)."},
    {"name": "Wand of Lightning Bolts", "category": "wand", "rarity": "rare", "cost": "32000 gp", "attunement": True, "weight": "1 lb.",
     "description": "This wand has 7 charges. While holding it, you can use an action to expend 1 or more charges to cast Lightning Bolt (save DC 15)."},
    {"name": "Wand of Paralysis", "category": "wand", "rarity": "rare", "cost": "16000 gp", "attunement": True, "weight": "1 lb.",
     "description": "This wand has 7 charges. You can use an action to expend 1 charge to cause a creature to make a DC 15 Con save or be paralyzed for 1 minute."},

    # ── Wondrous Items ───────────────────────────────────────────────────
    {"name": "Bag of Holding", "category": "wondrous", "rarity": "uncommon", "cost": "400 gp", "weight": "15 lb.",
     "description": "This bag has an interior space considerably larger than its outside dimensions — roughly 2 feet in diameter and 4 feet deep. It can hold up to 500 pounds, not exceeding 64 cubic feet."},
    {"name": "Boots of Elvenkind", "category": "wondrous", "rarity": "uncommon", "cost": "2500 gp", "weight": "1 lb.",
     "description": "While you wear these boots, your steps make no sound, regardless of the surface. You have advantage on Dexterity (Stealth) checks that rely on moving silently."},
    {"name": "Boots of Striding and Springing", "category": "wondrous", "rarity": "uncommon", "cost": "5000 gp", "attunement": True, "weight": "1 lb.",
     "description": "Your walking speed becomes 30 feet unless it is already higher. Your jump distance is tripled."},
    {"name": "Bracers of Archery", "category": "wondrous", "rarity": "uncommon", "cost": "1500 gp", "attunement": True, "weight": "—",
     "description": "While wearing these bracers, you have proficiency with the longbow and shortbow, and you gain a +2 bonus to damage rolls on ranged attacks made with such weapons."},
    {"name": "Bracers of Defense", "category": "wondrous", "rarity": "rare", "cost": "6000 gp", "attunement": True, "weight": "—",
     "description": "While wearing these bracers, you gain a +2 bonus to AC if you are wearing no armor and using no shield."},
    {"name": "Cloak of Elvenkind", "category": "wondrous", "rarity": "uncommon", "cost": "5000 gp", "attunement": True, "weight": "1 lb.",
     "description": "While you wear this cloak with its hood up, Wisdom (Perception) checks made to see you have disadvantage, and you have advantage on Dexterity (Stealth) checks."},
    {"name": "Cloak of Protection", "category": "wondrous", "rarity": "uncommon", "cost": "3500 gp", "attunement": True, "weight": "1 lb.",
     "description": "You gain a +1 bonus to AC and saving throws while you wear this cloak."},
    {"name": "Cloak of the Manta Ray", "category": "wondrous", "rarity": "uncommon", "cost": "6000 gp", "weight": "1 lb.",
     "description": "While wearing this cloak with its hood up, you can breathe underwater and have a swimming speed of 60 feet."},
    {"name": "Decanter of Endless Water", "category": "wondrous", "rarity": "uncommon", "cost": "13500 gp", "weight": "2 lb.",
     "description": "This stoppered flask sloshes when shaken. You can use an action to remove the stopper and speak one of three command words to produce fresh or salt water."},
    {"name": "Dust of Disappearance", "category": "wondrous", "rarity": "uncommon", "cost": "300 gp", "weight": "—",
     "description": "Found in a small packet, this powder resembles very fine sand. One use makes you and everything you wear or carry invisible for 2d4 minutes."},
    {"name": "Eyes of the Eagle", "category": "wondrous", "rarity": "uncommon", "cost": "2500 gp", "attunement": True, "weight": "—",
     "description": "These crystal lenses fit over the eyes. You have advantage on Wisdom (Perception) checks that rely on sight, and you can see details at extreme distances."},
    {"name": "Gauntlets of Ogre Power", "category": "wondrous", "rarity": "uncommon", "cost": "8000 gp", "attunement": True, "weight": "1 lb.",
     "description": "Your Strength score is 19 while you wear these gauntlets."},
    {"name": "Gem of Brightness", "category": "wondrous", "rarity": "uncommon", "cost": "5000 gp", "weight": "—",
     "description": "This prism has 50 charges. You can use an action to speak a command word and cause the gem to shed bright light in a 30-foot radius."},
    {"name": "Goggles of Night", "category": "wondrous", "rarity": "uncommon", "cost": "1500 gp", "weight": "—",
     "description": "While wearing these dark lenses, you have darkvision out to a range of 60 feet."},
    {"name": "Headband of Intellect", "category": "wondrous", "rarity": "uncommon", "cost": "8000 gp", "attunement": True, "weight": "—",
     "description": "Your Intelligence score is 19 while you wear this headband."},
    {"name": "Helm of Comprehending Languages", "category": "wondrous", "rarity": "uncommon", "cost": "500 gp", "weight": "2 lb.",
     "description": "While wearing this helm, you can use an action to cast the Comprehend Languages spell from it at will."},
    {"name": "Immovable Rod", "category": "wondrous", "rarity": "uncommon", "cost": "5000 gp", "weight": "2 lb.",
     "description": "This flat iron rod has a button on one end. You can use an action to press the button, which causes the rod to become magically fixed in place."},
    {"name": "Lantern of Revealing", "category": "wondrous", "rarity": "uncommon", "cost": "5000 gp", "weight": "2 lb.",
     "description": "While lit, this hooded lantern burns for 6 hours on 1 pint of oil, shedding bright light in a 30-foot radius and revealing invisible creatures and objects."},
    {"name": "Necklace of Fireballs", "category": "wondrous", "rarity": "rare", "cost": "5000 gp", "weight": "1 lb.",
     "description": "This necklace has 1d6+3 beads hanging from it. You can use an action to detach a bead and throw it up to 60 feet, creating a Fireball effect."},
    {"name": "Pearl of Power", "category": "wondrous", "rarity": "uncommon", "cost": "6000 gp", "attunement": True, "weight": "—",
     "description": "While this pearl is on your person, you can use an action to speak its command word and regain one expended spell slot of up to 3rd level."},
    {"name": "Periapt of Wound Closure", "category": "wondrous", "rarity": "uncommon", "cost": "5000 gp", "attunement": True, "weight": "—",
     "description": "While you wear this pendant, you stabilize whenever you are dying at the start of your turn, and whenever you roll a Hit Die to regain hit points, double the number."},
    {"name": "Quiver of Ehlonna", "category": "wondrous", "rarity": "uncommon", "cost": "1000 gp", "weight": "2 lb.",
     "description": "This quiver has three compartments: one holds 60 arrows, one holds 18 javelins, and one holds 6 long objects (bows, quarterstaffs, spears)."},
    {"name": "Robe of Useful Items", "category": "wondrous", "rarity": "uncommon", "cost": "2000 gp", "weight": "1 lb.",
     "description": "This robe has cloth patches of various shapes and colors covering it. While wearing the robe, you can use an action to detach one of the patches."},
    {"name": "Rope of Climbing", "category": "wondrous", "rarity": "uncommon", "cost": "2000 gp", "weight": "3 lb.",
     "description": "This 60-foot length of silk rope weighs 3 pounds and can hold up to 3,000 pounds. You can use a bonus action to command the rope to move."},
    {"name": "Sending Stones", "category": "wondrous", "rarity": "uncommon", "cost": "2200 gp", "weight": "—",
     "description": "Sending stones come in pairs. While you touch one stone, you can use an action to cast the Sending spell from it. Once used, can't be used again until next dawn."},
    {"name": "Slippers of Spider Climbing", "category": "wondrous", "rarity": "uncommon", "cost": "5000 gp", "attunement": True, "weight": "—",
     "description": "While you wear these light shoes, you can move up, down, and across vertical surfaces and upside down along ceilings, leaving your hands free."},
    {"name": "Stone of Good Luck", "category": "wondrous", "rarity": "uncommon", "cost": "4200 gp", "attunement": True, "weight": "—",
     "description": "While this polished agate is on your person, you gain a +1 bonus to ability checks and saving throws."},
    {"name": "Winged Boots", "category": "wondrous", "rarity": "uncommon", "cost": "8000 gp", "attunement": True, "weight": "1 lb.",
     "description": "While you wear these boots, you have a flying speed equal to your walking speed. You can fly for up to 4 hours per day."},

    # ── Gear / Tools ─────────────────────────────────────────────────────
    {"name": "Healer's Kit", "category": "gear", "rarity": "common", "cost": "5 gp", "weight": "3 lb.",
     "description": "This kit is a leather pouch containing bandages, salves, and splints. The kit has ten uses. As an action, you can expend one use to stabilize a creature at 0 HP."},
    {"name": "Thieves' Tools", "category": "tool", "rarity": "common", "cost": "25 gp", "weight": "1 lb.",
     "description": "This set of tools includes a small file, a set of lock picks, a small mirror, a set of narrow-bladed scissors, and a pair of pliers."},
    {"name": "Disguise Kit", "category": "tool", "rarity": "common", "cost": "25 gp", "weight": "3 lb.",
     "description": "This pouch of cosmetics, hair dye, and small props lets you create disguises."},
    {"name": "Herbalism Kit", "category": "tool", "rarity": "common", "cost": "5 gp", "weight": "3 lb.",
     "description": "This kit contains a variety of instruments such as clippers, mortar and pestle, and pouches used to create remedies and potions."},
    {"name": "Poisoner's Kit", "category": "tool", "rarity": "common", "cost": "50 gp", "weight": "2 lb.",
     "description": "A poisoner's kit includes the vials, chemicals, and other equipment necessary for the creation of poisons."},
    {"name": "Forgery Kit", "category": "tool", "rarity": "common", "cost": "15 gp", "weight": "5 lb.",
     "description": "This small box contains a variety of papers, parchments, pens and inks, seals, gold leaf, and other supplies necessary to create convincing forgeries."},
    {"name": "Navigator's Tools", "category": "tool", "rarity": "common", "cost": "25 gp", "weight": "2 lb.",
     "description": "This set of instruments is used for navigation at sea. Proficiency lets you chart a ship's course and follow navigation charts."},
    {"name": "Alchemist's Supplies", "category": "tool", "rarity": "common", "cost": "50 gp", "weight": "8 lb.",
     "description": "These special tools include the items needed to pursue alchemy."},
    {"name": "Calligrapher's Supplies", "category": "tool", "rarity": "common", "cost": "10 gp", "weight": "5 lb.",
     "description": "These tools include ink, a dozen sheets of parchment, and three quills."},
    {"name": "Carpenter's Tools", "category": "tool", "rarity": "common", "cost": "8 gp", "weight": "6 lb.",
     "description": "These special tools include the items needed to pursue carpentry."},
    {"name": "Climber's Kit", "category": "gear", "rarity": "common", "cost": "25 gp", "weight": "12 lb.",
     "description": "A climber's kit includes special pitons, boot tips, gloves, and a harness. As an action, you can anchor yourself."},
    {"name": "Holy Water", "category": "potion", "rarity": "common", "cost": "25 gp", "weight": "1 lb.",
     "description": "As an action, you can splash the contents of this flask onto a creature within 5 feet or throw it up to 20 feet. A fiend or undead takes 2d6 radiant damage."},
    {"name": "Alchemist's Fire", "category": "potion", "rarity": "common", "cost": "50 gp", "weight": "1 lb.",
     "description": "This sticky, adhesive fluid ignites when exposed to air. As an action, throw this flask up to 20 feet. On impact, target takes 1d4 fire damage at the start of each of its turns."},

    # ── Magic Weapons ────────────────────────────────────────────────────
    {"name": "+1 Weapon", "category": "weapon", "rarity": "uncommon", "cost": "1000 gp", "weight": "varies",
     "description": "You have a +1 bonus to attack and damage rolls made with this magic weapon."},
    {"name": "+2 Weapon", "category": "weapon", "rarity": "rare", "cost": "5000 gp", "weight": "varies",
     "description": "You have a +2 bonus to attack and damage rolls made with this magic weapon."},
    {"name": "+3 Weapon", "category": "weapon", "rarity": "very_rare", "cost": "50000 gp", "weight": "varies",
     "description": "You have a +3 bonus to attack and damage rolls made with this magic weapon."},
    {"name": "Flame Tongue", "category": "weapon", "rarity": "rare", "cost": "5000 gp", "attunement": True, "weight": "varies",
     "description": "You can use a bonus action to speak this magic sword's command word, causing flames to erupt. The flames shed bright light and deal an extra 2d6 fire damage."},
    {"name": "Frost Brand", "category": "weapon", "rarity": "very_rare", "cost": "22000 gp", "attunement": True, "weight": "varies",
     "description": "When you hit with an attack using this sword, the target takes an extra 1d6 cold damage. You have resistance to fire damage."},
    {"name": "Vicious Weapon", "category": "weapon", "rarity": "rare", "cost": "5000 gp", "weight": "varies",
     "description": "When you roll a 20 on your attack roll with this magic weapon, the target takes an extra 2d6 damage of the weapon's type."},
    {"name": "Weapon of Warning", "category": "weapon", "rarity": "uncommon", "cost": "6000 gp", "attunement": True, "weight": "varies",
     "description": "This magic weapon warns you of danger. While it is on your person, you have advantage on initiative rolls and you can't be surprised."},
    {"name": "Dragon Slayer", "category": "weapon", "rarity": "rare", "cost": "8000 gp", "weight": "varies",
     "description": "You gain a +1 bonus to attack and damage rolls made with this magic weapon. When you hit a dragon, the dragon takes an extra 3d6 damage."},
    {"name": "Giant Slayer", "category": "weapon", "rarity": "rare", "cost": "7000 gp", "weight": "varies",
     "description": "You gain a +1 bonus to attack and damage rolls. When you hit a giant, it takes an extra 2d6 damage and must succeed on a DC 15 Str save or fall prone."},
    {"name": "Arrow of Slaying", "category": "weapon", "rarity": "very_rare", "cost": "2500 gp", "weight": "—",
     "description": "An arrow of slaying is a magic weapon meant to slay a particular kind of creature. If the target fails a DC 17 Con save, it takes an extra 6d10 piercing damage."},
    {"name": "Javelin of Lightning", "category": "weapon", "rarity": "uncommon", "cost": "1500 gp", "weight": "2 lb.",
     "description": "This javelin is a magic weapon. When you hurl it and speak its command word, it transforms into a bolt of lightning, forming a 5-foot-wide line 120 feet long."},
    {"name": "Oathbow", "category": "weapon", "rarity": "very_rare", "cost": "3500 gp", "attunement": True, "weight": "2 lb.",
     "description": "When you nock an arrow on this bow, it whispers in Elvish, 'Swift defeat to my enemies.' You can swear an oath against a foe, gaining advantage and +3d6 piercing damage."},
    {"name": "Sword of Life Stealing", "category": "weapon", "rarity": "rare", "cost": "10000 gp", "attunement": True, "weight": "varies",
     "description": "When you attack a creature with this magic weapon and roll a 20, the target takes an extra 3d6 necrotic damage and you gain temporary HP equal to the extra damage."},
    {"name": "Sword of Sharpness", "category": "weapon", "rarity": "very_rare", "cost": "42000 gp", "attunement": True, "weight": "varies",
     "description": "When you attack an object or a creature with this magic weapon and roll a 20, the target takes an extra 4d6 slashing damage."},
    {"name": "Sword of Wounding", "category": "weapon", "rarity": "rare", "cost": "2000 gp", "attunement": True, "weight": "varies",
     "description": "Hit points lost to this weapon's damage can be regained only through a short or long rest, rather than by regeneration, magic, or any other means."},
    {"name": "Trident of Fish Command", "category": "weapon", "rarity": "uncommon", "cost": "800 gp", "attunement": True, "weight": "4 lb.",
     "description": "This trident is a magic weapon. It has 3 charges. You can expend 1 charge to cast Dominate Beast on a beast with an innate swimming speed (save DC 15)."},
    {"name": "Dagger of Venom", "category": "weapon", "rarity": "rare", "cost": "2500 gp", "weight": "1 lb.",
     "description": "You can use an action to cause thick, black poison to coat the blade. The poison remains for 1 minute. A creature hit takes an extra 2d10 poison damage (DC 15 Con for half)."},
    {"name": "Mace of Disruption", "category": "weapon", "rarity": "rare", "cost": "8000 gp", "attunement": True, "weight": "4 lb.",
     "description": "When you hit a fiend or undead with this magic weapon, it takes an extra 2d6 radiant damage. If the target has 25 HP or fewer, it must succeed on a DC 15 Wis save or be destroyed."},
    {"name": "Mace of Smiting", "category": "weapon", "rarity": "rare", "cost": "7000 gp", "weight": "4 lb.",
     "description": "You gain a +1 bonus to attack and damage rolls with this magic weapon. When you hit a construct, it takes an extra 2d6 bludgeoning damage."},
    {"name": "Mace of Terror", "category": "weapon", "rarity": "rare", "cost": "8000 gp", "attunement": True, "weight": "4 lb.",
     "description": "This magic weapon has 3 charges. While holding it, you can use an action and expend 1 charge to release a wave of terror (DC 15 Wis save or frightened for 1 minute)."},
    {"name": "Sun Blade", "category": "weapon", "rarity": "rare", "cost": "12000 gp", "attunement": True, "weight": "3 lb.",
     "description": "This item appears to be a longsword hilt. While grasping the hilt, you can use a bonus action to cause a blade of pure radiance to spring into existence, dealing radiant damage."},
    {"name": "Dwarven Thrower", "category": "weapon", "rarity": "very_rare", "cost": "18000 gp", "attunement": True, "weight": "2 lb.",
     "description": "You gain a +3 bonus to attack and damage rolls with this magic warhammer. It has the thrown property (range 20/60) and returns to your hand after the attack."},
    {"name": "Hammer of Thunderbolts", "category": "weapon", "rarity": "legendary", "cost": "50000 gp", "weight": "10 lb.",
     "description": "You gain a +1 bonus to attack and damage rolls with this magic maul. While attuned to both Gauntlets of Ogre Power and a Belt of Giant Strength, the bonus becomes +3. The hammer has 5 charges."},
    {"name": "Nine Lives Stealer", "category": "weapon", "rarity": "very_rare", "cost": "16000 gp", "attunement": True, "weight": "varies",
     "description": "You gain a +2 bonus to attack and damage rolls with this magic sword. The sword has 1d8+1 charges. If you score a critical hit against a creature with fewer than 100 HP, it must succeed on a DC 15 Con save or be slain instantly."},
    {"name": "Sword of Vengeance", "category": "weapon", "rarity": "uncommon", "cost": "2500 gp", "attunement": True, "weight": "varies",
     "description": "You gain a +1 bonus to attack and damage rolls with this cursed magic sword. While you are attuned, you are unwilling to part with it, and you have disadvantage on attack rolls with other weapons."},
    {"name": "Berserker Axe", "category": "weapon", "rarity": "rare", "cost": "6000 gp", "attunement": True, "weight": "4 lb.",
     "description": "You gain a +1 bonus to attack and damage rolls with this cursed magic weapon. When you take damage, you must succeed on a DC 15 Wis save or go berserk."},

    # ── Magic Armor ──────────────────────────────────────────────────────
    {"name": "+1 Shield", "category": "armor", "rarity": "uncommon", "cost": "1500 gp", "weight": "6 lb.",
     "description": "While holding this shield, you have a +1 bonus to AC. This bonus is in addition to the shield's normal bonus.", "armor_type": "shield", "ac": 3},
    {"name": "+1 Armor", "category": "armor", "rarity": "rare", "cost": "1500 gp", "weight": "varies",
     "description": "You have a +1 bonus to AC while wearing this armor.", "armor_type": "medium", "ac": 1},
    {"name": "+2 Armor", "category": "armor", "rarity": "very_rare", "cost": "6000 gp", "weight": "varies",
     "description": "You have a +2 bonus to AC while wearing this armor.", "armor_type": "medium", "ac": 2},
    {"name": "+3 Armor", "category": "armor", "rarity": "legendary", "cost": "24000 gp", "weight": "varies",
     "description": "You have a +3 bonus to AC while wearing this armor.", "armor_type": "medium", "ac": 3},
    {"name": "Adamantine Armor", "category": "armor", "rarity": "uncommon", "cost": "500 gp", "weight": "varies",
     "description": "This suit of armor is reinforced with adamantine. While you're wearing it, any critical hit against you becomes a normal hit."},
    {"name": "Mithral Armor", "category": "armor", "rarity": "uncommon", "cost": "800 gp", "weight": "varies",
     "description": "Mithral is a light, flexible metal. If the armor normally imposes disadvantage on Stealth checks or has a Strength requirement, the mithral version doesn't."},
    {"name": "Armor of Resistance", "category": "armor", "rarity": "rare", "cost": "6000 gp", "attunement": True, "weight": "varies",
     "description": "You have resistance to one damage type while wearing this armor (chosen by the DM)."},
    {"name": "Armor of Vulnerability", "category": "armor", "rarity": "rare", "cost": "3000 gp", "attunement": True, "weight": "varies",
     "description": "Cursed armor. While wearing it, you have resistance to one type of damage (bludgeoning/piercing/slashing) and vulnerability to the other two."},
    {"name": "Elven Chain", "category": "armor", "rarity": "rare", "cost": "5000 gp", "weight": "20 lb.",
     "description": "You gain a +1 bonus to AC while wearing this armor. You are considered proficient even if you lack proficiency with medium armor.", "armor_type": "medium", "ac": 14},
    {"name": "Glamoured Studded Leather", "category": "armor", "rarity": "rare", "cost": "2000 gp", "weight": "13 lb.",
     "description": "While wearing this armor, you gain a +1 bonus to AC. You can use a bonus action to make the armor assume the appearance of normal clothing or another type of armor."},
    {"name": "Plate Armor of Etherealness", "category": "armor", "rarity": "legendary", "cost": "48000 gp", "attunement": True, "weight": "65 lb.",
     "description": "While wearing this armor, you can use an action to cast the Etherealness spell, lasting for up to 10 minutes. Once used, can't be used again until next dawn."},
    {"name": "Demon Armor", "category": "armor", "rarity": "very_rare", "cost": "20000 gp", "attunement": True, "weight": "65 lb.",
     "description": "Cursed plate armor. While wearing it, you gain a +1 bonus to AC, you can speak and understand Abyssal, and your unarmed strikes deal 1d8 magical slashing damage."},
    {"name": "Dragon Scale Mail", "category": "armor", "rarity": "very_rare", "cost": "40000 gp", "attunement": True, "weight": "45 lb.",
     "description": "Made from the scales of one kind of dragon, you gain a +1 bonus to AC, resistance to that dragon's damage type, and advantage on saves against dragon Frightful Presence."},
    {"name": "Dwarven Plate", "category": "armor", "rarity": "very_rare", "cost": "25000 gp", "weight": "65 lb.",
     "description": "While wearing this armor, you gain a +2 bonus to AC. If an effect moves you against your will, you can use your reaction to reduce the distance by up to 10 feet."},
    {"name": "Plate Armor of Invulnerability", "category": "armor", "rarity": "legendary", "cost": "45000 gp", "attunement": True, "weight": "65 lb.",
     "description": "You have resistance to nonmagical damage while wearing this armor. You can use an action to become immune to nonmagical damage for 10 minutes (1/day)."},
]


async def seed():
    await connect_db()
    pool = get_pool()

    count = await pool.fetchval("SELECT count(*) FROM items")
    if count > 0:
        print(f"Items table already has {count} entries. Skipping seed.")
        await close_db()
        return

    inserted = 0
    import json as _json
    for item in ITEMS:
        try:
            await pool.execute(
                """
                INSERT INTO items (name, category, rarity, attunement, cost, weight,
                    description, properties, damage, ac, armor_type)
                VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
                """,
                item["name"],
                item["category"],
                item["rarity"],
                item.get("attunement", False),
                item.get("cost"),
                item.get("weight"),
                item["description"],
                _json.dumps(item.get("properties", [])),
                item.get("damage"),
                item.get("ac"),
                item.get("armor_type"),
            )
            inserted += 1
        except Exception as e:
            print(f"  Skipped {item['name']}: {e}")

    print(f"Seeded {inserted} items.")
    await close_db()


if __name__ == "__main__":
    asyncio.run(seed())
