"""
Seed the spells table with SRD 5.1 spells.
Run: uv run python scripts/seed_spells.py
"""
import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "backend"))

from app.db import connect_db, close_db, get_pool

SPELLS = [
    {"name":"Acid Splash","level":0,"school":"conjuration","casting_time":"1 action","range":"60 feet","components":"V, S","duration":"Instantaneous","description":"You hurl a bubble of acid. Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. A target must succeed on a Dexterity saving throw or take 1d6 acid damage.","classes":["sorcerer","wizard"],"ritual":False,"concentration":False},
    {"name":"Fire Bolt","level":0,"school":"evocation","casting_time":"1 action","range":"120 feet","components":"V, S","duration":"Instantaneous","description":"You hurl a mote of fire at a creature or object within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 fire damage. A flammable object hit by this spell ignites if it isn't being worn or carried.","higher_level":"This spell's damage increases by 1d10 when you reach 5th level (2d10), 11th level (3d10), and 17th level (4d10).","classes":["sorcerer","wizard"],"ritual":False,"concentration":False},
    {"name":"Mage Hand","level":0,"school":"conjuration","casting_time":"1 action","range":"30 feet","components":"V, S","duration":"1 minute","description":"A spectral, floating hand appears at a point you choose within range. The hand lasts for the duration or until you dismiss it as an action. You can use the hand to manipulate an object, open an unlocked door or container, stow or retrieve an item from an open container, or pour the contents out of a vial.","classes":["bard","sorcerer","warlock","wizard"],"ritual":False,"concentration":False},
    {"name":"Prestidigitation","level":0,"school":"transmutation","casting_time":"1 action","range":"10 feet","components":"V, S","duration":"Up to 1 hour","description":"This spell is a minor magical trick that novice spellcasters use for practice. You create one of the following magical effects within range: an instantaneous harmless sensory effect; light or snuff a candle; clean or soil an object; chill, warm, or flavor nonliving material; make a symbol or mark appear; or create a nonmagical trinket.","classes":["bard","sorcerer","warlock","wizard"],"ritual":False,"concentration":False},
    {"name":"Guidance","level":0,"school":"divination","casting_time":"1 action","range":"Touch","components":"V, S","duration":"Concentration, up to 1 minute","description":"You touch one willing creature. Once before the spell ends, the target can roll a d4 and add the number rolled to one ability check of its choice. It can roll the die before or after making the ability check. The spell then ends.","classes":["cleric","druid"],"ritual":False,"concentration":True},
    {"name":"Sacred Flame","level":0,"school":"evocation","casting_time":"1 action","range":"60 feet","components":"V, S","duration":"Instantaneous","description":"Flame-like radiance descends on a creature that you can see within range. The target must succeed on a Dexterity saving throw or take 1d8 radiant damage. The target gains no benefit from cover for this saving throw.","higher_level":"The spell's damage increases by 1d8 when you reach 5th level (2d8), 11th level (3d8), and 17th level (4d8).","classes":["cleric"],"ritual":False,"concentration":False},
    {"name":"Eldritch Blast","level":0,"school":"evocation","casting_time":"1 action","range":"120 feet","components":"V, S","duration":"Instantaneous","description":"A beam of crackling energy streaks toward a creature within range. Make a ranged spell attack against the target. On a hit, the target takes 1d10 force damage.","higher_level":"The spell creates more than one beam when you reach higher levels: two beams at 5th level, three beams at 11th level, and four beams at 17th level.","classes":["warlock"],"ritual":False,"concentration":False},
    {"name":"Magic Missile","level":1,"school":"evocation","casting_time":"1 action","range":"120 feet","components":"V, S","duration":"Instantaneous","description":"You create three glowing darts of magical force. Each dart hits a creature of your choice that you can see within range. A dart deals 1d4+1 force damage to its target. The darts all strike simultaneously, and you can direct them to hit one creature or several.","higher_level":"When you cast this spell using a spell slot of 2nd level or higher, the spell creates one more dart for each slot level above 1st.","classes":["sorcerer","wizard"],"ritual":False,"concentration":False},
    {"name":"Shield","level":1,"school":"abjuration","casting_time":"1 reaction","range":"Self","components":"V, S","duration":"1 round","description":"An invisible barrier of magical force appears and protects you. Until the start of your next turn, you have a +5 bonus to AC, including against the triggering attack, and you take no damage from magic missile.","classes":["sorcerer","wizard"],"ritual":False,"concentration":False},
    {"name":"Cure Wounds","level":1,"school":"evocation","casting_time":"1 action","range":"Touch","components":"V, S","duration":"Instantaneous","description":"A creature you touch regains a number of hit points equal to 1d8 + your spellcasting ability modifier. This spell has no effect on undead or constructs.","higher_level":"When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d8 for each slot level above 1st.","classes":["bard","cleric","druid","paladin","ranger"],"ritual":False,"concentration":False},
    {"name":"Healing Word","level":1,"school":"evocation","casting_time":"1 bonus action","range":"60 feet","components":"V","duration":"Instantaneous","description":"A creature of your choice that you can see within range regains hit points equal to 1d4 + your spellcasting ability modifier. This spell has no effect on undead or constructs.","higher_level":"When you cast this spell using a spell slot of 2nd level or higher, the healing increases by 1d4 for each slot level above 1st.","classes":["bard","cleric","druid"],"ritual":False,"concentration":False},
    {"name":"Detect Magic","level":1,"school":"divination","casting_time":"1 action","range":"Self","components":"V, S","duration":"Concentration, up to 10 minutes","description":"For the duration, you sense the presence of magic within 30 feet of you. If you sense magic in this way, you can use your action to see a faint aura around any visible creature or object in the area that bears magic, and you learn its school of magic, if any.","classes":["bard","cleric","druid","paladin","ranger","sorcerer","wizard"],"ritual":True,"concentration":True},
    {"name":"Burning Hands","level":1,"school":"evocation","casting_time":"1 action","range":"Self (15-foot cone)","components":"V, S","duration":"Instantaneous","description":"As you hold your hands with thumbs touching and fingers spread, a thin sheet of flames shoots forth from your outstretched fingertips. Each creature in a 15-foot cone must make a Dexterity saving throw. A creature takes 3d6 fire damage on a failed save, or half as much damage on a successful one.","higher_level":"When you cast this spell using a spell slot of 2nd level or higher, the damage increases by 1d6 for each slot level above 1st.","classes":["sorcerer","wizard"],"ritual":False,"concentration":False},
    {"name":"Misty Step","level":2,"school":"conjuration","casting_time":"1 bonus action","range":"Self","components":"V","duration":"Instantaneous","description":"Briefly surrounded by silvery mist, you teleport up to 30 feet to an unoccupied space that you can see.","classes":["sorcerer","warlock","wizard"],"ritual":False,"concentration":False},
    {"name":"Invisibility","level":2,"school":"illusion","casting_time":"1 action","range":"Touch","components":"V, S, M (an eyelash encased in gum arabic)","duration":"Concentration, up to 1 hour","description":"A creature you touch becomes invisible until the spell ends. Anything the target is wearing or carrying is invisible as long as it is on the target's person.","higher_level":"When you cast this spell using a spell slot of 3rd level or higher, you can target one additional creature for each slot level above 2nd.","classes":["bard","sorcerer","warlock","wizard"],"ritual":False,"concentration":True},
    {"name":"Fireball","level":3,"school":"evocation","casting_time":"1 action","range":"150 feet","components":"V, S, M (a tiny ball of bat guano and sulfur)","duration":"Instantaneous","description":"A bright streak flashes from your pointing finger to a point you choose within range and then blossoms with a low roar into an explosion of flame. Each creature in a 20-foot-radius sphere centered on that point must make a Dexterity saving throw. A target takes 8d6 fire damage on a failed save, or half as much damage on a successful one.","higher_level":"When you cast this spell using a spell slot of 4th level or higher, the damage increases by 1d6 for each slot level above 3rd.","classes":["sorcerer","wizard"],"ritual":False,"concentration":False},
    {"name":"Counterspell","level":3,"school":"abjuration","casting_time":"1 reaction","range":"60 feet","components":"S","duration":"Instantaneous","description":"You attempt to interrupt a creature in the process of casting a spell. If the creature is casting a spell of 3rd level or lower, its spell fails and has no effect. If it is casting a spell of 4th level or higher, make an ability check using your spellcasting ability. The DC equals 10 + the spell's level. On a success, the creature's spell fails and has no effect.","higher_level":"When you cast this spell using a spell slot of 4th level or higher, the interrupted spell has no effect if its level is less than or equal to the level of the spell slot you used.","classes":["sorcerer","warlock","wizard"],"ritual":False,"concentration":False},
    {"name":"Haste","level":3,"school":"transmutation","casting_time":"1 action","range":"30 feet","components":"V, S, M (a shaving of licorice root)","duration":"Concentration, up to 1 minute","description":"Choose a willing creature that you can see within range. Until the spell ends, the target's speed is doubled, it gains a +2 bonus to AC, it has advantage on Dexterity saving throws, and it gains an additional action on each of its turns. That action can be used only to take the Attack (one weapon attack only), Dash, Disengage, Hide, or Use an Object action. When the spell ends, the target can't move or take actions until after its next turn.","classes":["sorcerer","wizard"],"ritual":False,"concentration":True},
    {"name":"Polymorph","level":4,"school":"transmutation","casting_time":"1 action","range":"60 feet","components":"V, S, M (a caterpillar cocoon)","duration":"Concentration, up to 1 hour","description":"This spell transforms a creature that you can see within range into a new form. An unwilling creature must make a Wisdom saving throw to avoid the effect. The transformation lasts for the duration, or until the target drops to 0 hit points or dies. The new form can be any beast whose challenge rating is equal to or less than the target's (or the target's level, if it doesn't have a challenge rating).","classes":["bard","druid","sorcerer","wizard"],"ritual":False,"concentration":True},
    {"name":"Wall of Force","level":5,"school":"evocation","casting_time":"1 action","range":"120 feet","components":"V, S, M (a pinch of powder made by crushing a clear gemstone)","duration":"Concentration, up to 10 minutes","description":"An invisible wall of force springs into existence at a point you choose within range. The wall appears in any orientation you choose, as a horizontal or vertical barrier or at an angle. It can be free floating or resting on a solid surface. Nothing can physically pass through the wall. It is immune to all damage and can't be dispelled by dispel magic.","classes":["wizard"],"ritual":False,"concentration":True},
    {"name":"Heal","level":6,"school":"evocation","casting_time":"1 action","range":"60 feet","components":"V, S","duration":"Instantaneous","description":"Choose a creature that you can see within range. A surge of positive energy washes through the creature, causing it to regain 70 hit points. This spell also ends blindness, deafness, and any diseases affecting the target. This spell has no effect on constructs or undead.","higher_level":"When you cast this spell using a spell slot of 7th level or higher, the amount of healing increases by 10 for each slot level above 6th.","classes":["cleric","druid"],"ritual":False,"concentration":False},
    {"name":"Teleport","level":7,"school":"conjuration","casting_time":"1 action","range":"10 feet","components":"V","duration":"Instantaneous","description":"This spell instantly transports you and up to eight willing creatures of your choice that you can see within range, or a single object that you can see within range, to a destination you select. If you target an object, it must be able to fit entirely inside a 10-foot cube, and it can't be held or carried by an unwilling creature.","classes":["bard","sorcerer","wizard"],"ritual":False,"concentration":False},
    {"name":"Power Word Stun","level":8,"school":"enchantment","casting_time":"1 action","range":"60 feet","components":"V","duration":"Instantaneous","description":"You speak a word of power that can overwhelm the mind of one creature you can see within range, leaving it dumbfounded. If the target has 150 hit points or fewer, it is stunned. Otherwise, the spell has no effect. The stunned target must make a Constitution saving throw at the end of each of its turns. On a successful save, this stunning effect ends.","classes":["bard","sorcerer","warlock","wizard"],"ritual":False,"concentration":False},
    {"name":"Meteor Swarm","level":9,"school":"evocation","casting_time":"1 action","range":"1 mile","components":"V, S","duration":"Instantaneous","description":"Blazing orbs of fire plummet to the ground at four different points you can see within range. Each creature in a 40-foot-radius sphere centered on each point you choose must make a Dexterity saving throw. A creature takes 20d6 fire damage and 20d6 bludgeoning damage on a failed save, or half as much damage on a successful one. A creature in the area of more than one fiery burst is affected only once.","classes":["sorcerer","wizard"],"ritual":False,"concentration":False},
    {"name":"Wish","level":9,"school":"conjuration","casting_time":"1 action","range":"Self","components":"V","duration":"Instantaneous","description":"Wish is the mightiest spell a mortal creature can cast. By simply speaking aloud, you can alter the very foundations of reality in accord with your desires. The basic use of this spell is to duplicate any other spell of 8th level or lower. You don't need to meet any requirements in that spell, including costly components. The spell simply takes effect. Alternatively, you can create one of the following effects of your choice: create a nonmagical object up to 25,000 gp in value; allow up to twenty creatures to regain all hit points; grant up to ten creatures resistance to a damage type; grant up to ten creatures immunity to a single spell or magical effect for 8 hours; or undo a single recent event.","classes":["sorcerer","wizard"],"ritual":False,"concentration":False},
]

async def seed():
    await connect_db()
    pool = get_pool()

    count = await pool.fetchval("SELECT count(*) FROM spells")
    if count > 0:
        print(f"Spells table already has {count} spells. Skipping seed.")
        await close_db()
        return

    inserted = 0
    for s in SPELLS:
        try:
            await pool.execute(
                """INSERT INTO spells (name, level, school, casting_time, range, components,
                    duration, description, higher_level, classes, ritual, concentration)
                VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)""",
                s["name"], s["level"], s["school"], s["casting_time"],
                s["range"], s["components"], s["duration"], s["description"],
                s.get("higher_level"), s["classes"], s["ritual"], s["concentration"],
            )
            inserted += 1
        except Exception as e:
            print(f"  Error inserting {s['name']}: {e}")

    print(f"✅ Seeded {inserted} spells into spellbook.")
    await close_db()

if __name__ == "__main__":
    asyncio.run(seed())
